import {
  User,
  Department,
  Team,
  Project,
  Task,
  Blocker,
  Meeting,
  LeaveRequest,
  WeeklyCheckin,
  Goal,
  AuditLog,
  NotificationItem,
  InsightCard,
} from './types';

export const INITIAL_DEPARTMENTS: Department[] = [
  { id: 'dept-1', name: 'Engineering', code: 'ENG', headName: 'Sarah Jenkins', memberCount: 14 },
  { id: 'dept-2', name: 'Product & Design', code: 'PROD', headName: 'Alex Rivera', memberCount: 7 },
  { id: 'dept-3', name: 'Marketing & Growth', code: 'MKTG', headName: 'Elena Rostova', memberCount: 5 },
  { id: 'dept-4', name: 'Operations & SecOps', code: 'OPS', headName: 'David Chen', memberCount: 4 },
  { id: 'dept-5', name: 'People & Culture', code: 'PEOPLE', headName: 'Rachel Vance', memberCount: 2 },
];

export const INITIAL_TEAMS: Team[] = [
  { id: 'team-1', name: 'Frontend Core', departmentId: 'dept-1', leadName: 'Marcus Wright', memberCount: 5 },
  { id: 'team-2', name: 'Backend & Platform', departmentId: 'dept-1', leadName: 'Vikram Mehta', memberCount: 5 },
  { id: 'team-3', name: 'Infrastructure & SRE', departmentId: 'dept-1', leadName: 'Liam O’Connor', memberCount: 4 },
  { id: 'team-4', name: 'Product Management', departmentId: 'dept-2', leadName: 'Alex Rivera', memberCount: 3 },
  { id: 'team-5', name: 'Product Design', departmentId: 'dept-2', leadName: 'Siddharth Rao', memberCount: 4 },
  { id: 'team-6', name: 'Growth Marketing', departmentId: 'dept-3', leadName: 'Elena Rostova', memberCount: 5 },
  { id: 'team-7', name: 'Operations & IT', departmentId: 'dept-4', leadName: 'David Chen', memberCount: 4 },
  { id: 'team-8', name: 'People Ops & HR', departmentId: 'dept-5', leadName: 'Rachel Vance', memberCount: 2 },
];

export const INITIAL_USERS: User[] = [
  {
    id: 'usr-1',
    name: 'V S Sai Siddardh',
    email: 'siddhardh@veixon.tech',
    avatarUrl: 'https://www.veixon.com/team/siddardha.png',
    jobTitle: 'Co-founder & Director',
    role: 'DIRECTOR',
    departmentId: 'dept-1',
    departmentName: 'Engineering',
    teamId: 'team-1',
    teamName: 'Frontend Core',
    attendanceStatus: 'WORKING',
    lastActiveAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    joinedAt: '2023-01-15T00:00:00Z',
    location: 'Hyderabad, IN',
    timezone: 'IST (UTC+5:30)',
    skills: ['Strategic Architecture', 'Operations', 'Leadership', 'AI Systems'],
    leaveBalance: { casualTotal: 12, casualUsed: 2, sickTotal: 10, sickUsed: 1, annualTotal: 18, annualUsed: 6 },
  },
  {
    id: 'usr-2',
    name: 'Abhinav Rishi',
    email: 'abhinav@veixon.tech',
    avatarUrl: 'https://www.veixon.com/team/Abhinav.png',
    jobTitle: 'Founder & CEO',
    role: 'ADMIN',
    departmentId: 'dept-1',
    departmentName: 'Executive Leadership',
    teamId: 'team-1',
    teamName: 'Executive',
    managerId: 'usr-1',
    managerName: 'V S Sai Siddardh',
    attendanceStatus: 'WORKING',
    lastActiveAt: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
    joinedAt: '2023-01-01T00:00:00Z',
    location: 'Hyderabad, IN',
    timezone: 'IST (UTC+5:30)',
    skills: ['Strategy', 'Company Vision', 'Business Intelligence', 'Leadership'],
    leaveBalance: { casualTotal: 12, casualUsed: 1, sickTotal: 10, sickUsed: 0, annualTotal: 18, annualUsed: 3 },
  },
  {
    id: 'usr-3',
    name: 'Shlok Karn',
    email: 'shlok@veixon.tech',
    avatarUrl: 'https://www.veixon.com/team/shlok.jpeg',
    jobTitle: 'Co-founder & CTO',
    role: 'MANAGER',
    departmentId: 'dept-1',
    departmentName: 'Engineering',
    teamId: 'team-2',
    teamName: 'Backend & Platform',
    managerId: 'usr-1',
    managerName: 'V S Sai Siddardh',
    attendanceStatus: 'WORKING',
    lastActiveAt: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
    joinedAt: '2023-01-15T00:00:00Z',
    location: 'Hyderabad, IN',
    timezone: 'IST (UTC+5:30)',
    skills: ['Distributed Systems', 'Platform Architecture', 'Cloud Infrastructure', 'Go'],
    leaveBalance: { casualTotal: 12, casualUsed: 3, sickTotal: 10, sickUsed: 0, annualTotal: 18, annualUsed: 4 },
  },
  {
    id: 'usr-4',
    name: 'Suhas',
    email: 'suhas@veixon.tech',
    avatarUrl: 'https://www.veixon.com/team/suhas.png',
    jobTitle: 'Cloud & Infrastructure Lead',
    role: 'EMPLOYEE',
    departmentId: 'dept-1',
    departmentName: 'Engineering',
    teamId: 'team-2',
    teamName: 'Backend & Platform',
    managerId: 'usr-3',
    managerName: 'Shlok Karn',
    attendanceStatus: 'ON_LEAVE', // Light blue: Leave on duty (informed)
    lastActiveAt: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    joinedAt: '2023-02-20T00:00:00Z',
    location: 'Hyderabad, IN',
    timezone: 'IST (UTC+5:30)',
    skills: ['PostgreSQL', 'Redis', 'Kubernetes', 'AWS KMS', 'Kafka'],
    leaveBalance: { casualTotal: 12, casualUsed: 1, sickTotal: 10, sickUsed: 1, annualTotal: 18, annualUsed: 5 },
  },
  {
    id: 'usr-5',
    name: 'Arjun J',
    email: 'arjun.j@veixon.tech',
    avatarUrl: 'https://www.veixon.com/team/ARJUN.png',
    jobTitle: 'Software Engineer',
    role: 'EMPLOYEE',
    departmentId: 'dept-1',
    departmentName: 'Engineering',
    teamId: 'team-1',
    teamName: 'Frontend Core',
    managerId: 'usr-1',
    managerName: 'V S Sai Siddardh',
    attendanceStatus: 'WORKING', // Green: Present
    lastActiveAt: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
    joinedAt: '2023-08-01T00:00:00Z',
    location: 'Hyderabad, IN',
    timezone: 'IST (UTC+5:30)',
    skills: ['TypeScript', 'React', 'Tailwind', 'REST APIs', 'Next.js'],
    leaveBalance: { casualTotal: 12, casualUsed: 1, sickTotal: 10, sickUsed: 0, annualTotal: 18, annualUsed: 2 },
  },
  {
    id: 'usr-6',
    name: 'Shabnam Nisha',
    email: 'shabnam@veixon.tech',
    avatarUrl: 'https://www.veixon.com/team/Shabnam.jpeg',
    jobTitle: 'Lead Product Designer',
    role: 'EMPLOYEE',
    departmentId: 'dept-2',
    departmentName: 'Product & Design',
    teamId: 'team-5',
    teamName: 'Product Design',
    managerId: 'usr-1',
    managerName: 'V S Sai Siddardh',
    attendanceStatus: 'WORKING',
    lastActiveAt: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
    joinedAt: '2023-04-15T00:00:00Z',
    location: 'Hyderabad, IN',
    timezone: 'IST (UTC+5:30)',
    skills: ['Figma', 'Design Systems', 'Micro-interactions', 'User Research'],
    leaveBalance: { casualTotal: 12, casualUsed: 3, sickTotal: 10, sickUsed: 1, annualTotal: 18, annualUsed: 4 },
  },
  {
    id: 'usr-7',
    name: 'C. Taran Teja',
    email: 'taran@veixon.tech',
    avatarUrl: 'https://www.veixon.com/team/taran.jpeg',
    jobTitle: 'Frontend Engineer',
    role: 'EMPLOYEE',
    departmentId: 'dept-1',
    departmentName: 'Engineering',
    teamId: 'team-1',
    teamName: 'Frontend Core',
    managerId: 'usr-1',
    managerName: 'V S Sai Siddardh',
    attendanceStatus: 'WORKING',
    lastActiveAt: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
    joinedAt: '2023-02-01T00:00:00Z',
    location: 'Hyderabad, IN',
    timezone: 'IST (UTC+5:30)',
    skills: ['Next.js', 'UI Performance', 'CSS Systems', 'Animations'],
    leaveBalance: { casualTotal: 12, casualUsed: 2, sickTotal: 10, sickUsed: 0, annualTotal: 18, annualUsed: 6 },
  },
  {
    id: 'usr-8',
    name: 'Navya',
    email: 'navya@veixon.tech',
    avatarUrl: 'https://www.veixon.com/team/NAVYA.jpeg',
    jobTitle: 'Head of People & Operations',
    role: 'HR',
    departmentId: 'dept-5',
    departmentName: 'People & Culture',
    teamId: 'team-8',
    teamName: 'People Ops & HR',
    attendanceStatus: 'WORKING',
    lastActiveAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    joinedAt: '2023-01-05T00:00:00Z',
    location: 'Hyderabad, IN',
    timezone: 'IST (UTC+5:30)',
    skills: ['Talent Ops', 'People Operations', 'Compliance', 'Team Culture'],
    leaveBalance: { casualTotal: 12, casualUsed: 1, sickTotal: 10, sickUsed: 0, annualTotal: 18, annualUsed: 3 },
  },
  {
    id: 'usr-9',
    name: 'Sreeshith',
    email: 'sreeshith@veixon.tech',
    avatarUrl: 'https://www.veixon.com/team/sreeshith.png',
    jobTitle: 'Lead DevOps / SRE',
    role: 'EMPLOYEE',
    departmentId: 'dept-1',
    departmentName: 'Engineering',
    teamId: 'team-3',
    teamName: 'Infrastructure & SRE',
    managerId: 'usr-3',
    managerName: 'Shlok Karn',
    attendanceStatus: 'WORKING',
    lastActiveAt: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
    joinedAt: '2023-05-12T00:00:00Z',
    location: 'Hyderabad, IN',
    timezone: 'IST (UTC+5:30)',
    skills: ['Terraform', 'AWS', 'Kubernetes', 'CI/CD Pipelines', 'Prometheus'],
    leaveBalance: { casualTotal: 12, casualUsed: 5, sickTotal: 10, sickUsed: 1, annualTotal: 18, annualUsed: 9 },
  },
  {
    id: 'usr-10',
    name: 'Shivani',
    email: 'shivani@veixon.tech',
    avatarUrl: 'https://www.veixon.com/team/shivani.jpeg',
    jobTitle: 'QA & Security Engineer',
    role: 'EMPLOYEE',
    departmentId: 'dept-1',
    departmentName: 'Engineering',
    teamId: 'team-1',
    teamName: 'Frontend Core',
    managerId: 'usr-1',
    managerName: 'V S Sai Siddardh',
    attendanceStatus: 'ABSENT', // Red: Leave without informing (actionable)
    lastActiveAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    joinedAt: '2023-03-15T00:00:00Z',
    location: 'Hyderabad, IN',
    timezone: 'IST (UTC+5:30)',
    skills: ['Security Auditing', 'Automated Testing', 'Cypress', 'Penetration Testing'],
    leaveBalance: { casualTotal: 12, casualUsed: 2, sickTotal: 10, sickUsed: 0, annualTotal: 18, annualUsed: 5 },
  },
  {
    id: 'usr-11',
    name: 'David Chen',
    email: 'david.chen@workpulse.io',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    jobTitle: 'Head of Operations & SecOps',
    role: 'MANAGER',
    departmentId: 'dept-4',
    departmentName: 'Operations & SecOps',
    teamId: 'team-7',
    teamName: 'Operations & IT',
    attendanceStatus: 'WORKING',
    lastActiveAt: new Date(Date.now() - 50 * 60 * 1000).toISOString(),
    joinedAt: '2023-02-15T00:00:00Z',
    location: 'San Jose, US',
    timezone: 'PST (UTC-8)',
    skills: ['SOC2 Compliance', 'Security Audits', 'IT Operations', 'Vendor Mgmt'],
    leaveBalance: { casualTotal: 12, casualUsed: 3, sickTotal: 10, sickUsed: 1, annualTotal: 18, annualUsed: 4 },
  },
  {
    id: 'usr-12',
    name: 'Kavita Nair',
    email: 'kavita.nair@workpulse.io',
    avatarUrl: 'https://images.unsplash.com/photo-1534751516642-a171edd2521d?w=150&auto=format&fit=crop&q=80',
    jobTitle: 'Senior Frontend Engineer',
    role: 'EMPLOYEE',
    departmentId: 'dept-1',
    departmentName: 'Engineering',
    teamId: 'team-1',
    teamName: 'Frontend Core',
    managerId: 'usr-7',
    managerName: 'Marcus Wright',
    attendanceStatus: 'WORKING',
    lastActiveAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    joinedAt: '2023-07-01T00:00:00Z',
    location: 'Bengaluru, IN',
    timezone: 'IST (UTC+5:30)',
    skills: ['React', 'TypeScript', 'State Management', 'WebSockets'],
    leaveBalance: { casualTotal: 12, casualUsed: 2, sickTotal: 10, sickUsed: 1, annualTotal: 18, annualUsed: 6 },
  },
  {
    id: 'usr-13',
    name: 'Carlos Mendez',
    email: 'carlos.mendez@workpulse.io',
    avatarUrl: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=150&auto=format&fit=crop&q=80',
    jobTitle: 'Senior Backend Engineer',
    role: 'EMPLOYEE',
    departmentId: 'dept-1',
    departmentName: 'Engineering',
    teamId: 'team-2',
    teamName: 'Backend & Platform',
    managerId: 'usr-2',
    managerName: 'Vikram Mehta',
    attendanceStatus: 'ON_LEAVE',
    lastActiveAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    joinedAt: '2023-04-01T00:00:00Z',
    location: 'Madrid, ES',
    timezone: 'CET (UTC+1)',
    skills: ['Python', 'FastAPI', 'PostgreSQL', 'Docker'],
    leaveBalance: { casualTotal: 12, casualUsed: 6, sickTotal: 10, sickUsed: 2, annualTotal: 18, annualUsed: 12 },
  },
  {
    id: 'usr-14',
    name: 'Zoe Dubois',
    email: 'zoe.dubois@workpulse.io',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    jobTitle: 'Product Manager - Core',
    role: 'EMPLOYEE',
    departmentId: 'dept-2',
    departmentName: 'Product & Design',
    teamId: 'team-4',
    teamName: 'Product Management',
    managerId: 'usr-5',
    managerName: 'Alex Rivera',
    attendanceStatus: 'WORKING',
    lastActiveAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    joinedAt: '2023-05-15T00:00:00Z',
    location: 'Paris, FR',
    timezone: 'CET (UTC+1)',
    skills: ['Feature Specs', 'Agile', 'Customer Interviews', 'Metrics'],
    leaveBalance: { casualTotal: 12, casualUsed: 3, sickTotal: 10, sickUsed: 0, annualTotal: 18, annualUsed: 5 },
  },
  {
    id: 'usr-15',
    name: 'Siddharth Rao',
    email: 'siddharth.rao@workpulse.io',
    avatarUrl: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=150&auto=format&fit=crop&q=80',
    jobTitle: 'Design Lead',
    role: 'MANAGER',
    departmentId: 'dept-2',
    departmentName: 'Product & Design',
    teamId: 'team-5',
    teamName: 'Product Design',
    managerId: 'usr-5',
    managerName: 'Alex Rivera',
    attendanceStatus: 'WORKING',
    lastActiveAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    joinedAt: '2023-03-10T00:00:00Z',
    location: 'Bengaluru, IN',
    timezone: 'IST (UTC+5:30)',
    skills: ['Visual Design', 'Interaction Design', 'Figma', 'Prototyping'],
    leaveBalance: { casualTotal: 12, casualUsed: 2, sickTotal: 10, sickUsed: 1, annualTotal: 18, annualUsed: 7 },
  },
  {
    id: 'usr-16',
    name: 'Aisha Al-Mansoor',
    email: 'aisha.mansoor@workpulse.io',
    avatarUrl: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=150&auto=format&fit=crop&q=80',
    jobTitle: 'Security & Compliance Engineer',
    role: 'EMPLOYEE',
    departmentId: 'dept-4',
    departmentName: 'Operations & SecOps',
    teamId: 'team-7',
    teamName: 'Operations & IT',
    managerId: 'usr-11',
    managerName: 'David Chen',
    attendanceStatus: 'WORKING',
    lastActiveAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    joinedAt: '2023-08-01T00:00:00Z',
    location: 'Dubai, UAE',
    timezone: 'GST (UTC+4)',
    skills: ['Pen Testing', 'SOC2', 'GDPR', 'IAM Policies'],
    leaveBalance: { casualTotal: 12, casualUsed: 1, sickTotal: 10, sickUsed: 0, annualTotal: 18, annualUsed: 2 },
  },
  {
    id: 'usr-17',
    name: 'Lucas Silva',
    email: 'lucas.silva@workpulse.io',
    avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    jobTitle: 'QA Automation Lead',
    role: 'EMPLOYEE',
    departmentId: 'dept-1',
    departmentName: 'Engineering',
    teamId: 'team-1',
    teamName: 'Frontend Core',
    managerId: 'usr-7',
    managerName: 'Marcus Wright',
    attendanceStatus: 'WORKING',
    lastActiveAt: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
    joinedAt: '2023-09-01T00:00:00Z',
    location: 'São Paulo, BR',
    timezone: 'BRT (UTC-3)',
    skills: ['Playwright', 'Cypress', 'Jest', 'CI Pipelines'],
    leaveBalance: { casualTotal: 12, casualUsed: 2, sickTotal: 10, sickUsed: 0, annualTotal: 18, annualUsed: 4 },
  },
  {
    id: 'usr-18',
    name: 'Maya Lin',
    email: 'maya.lin@workpulse.io',
    avatarUrl: 'https://images.unsplash.com/photo-1548142813-c348350df52b?w=150&auto=format&fit=crop&q=80',
    jobTitle: 'Content & Brand Strategist',
    role: 'EMPLOYEE',
    departmentId: 'dept-3',
    departmentName: 'Marketing & Growth',
    teamId: 'team-6',
    teamName: 'Growth Marketing',
    managerId: 'usr-10',
    managerName: 'Elena Rostova',
    attendanceStatus: 'WORKING',
    lastActiveAt: new Date(Date.now() - 14 * 60 * 1000).toISOString(),
    joinedAt: '2023-06-20T00:00:00Z',
    location: 'Singapore, SG',
    timezone: 'SGT (UTC+8)',
    skills: ['Technical Writing', 'Copywriting', 'SEO', 'Product Launches'],
    leaveBalance: { casualTotal: 12, casualUsed: 4, sickTotal: 10, sickUsed: 1, annualTotal: 18, annualUsed: 5 },
  },
  {
    id: 'usr-19',
    name: 'Oliver King',
    email: 'oliver.king@workpulse.io',
    avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    jobTitle: 'Cloud Architect',
    role: 'EMPLOYEE',
    departmentId: 'dept-1',
    departmentName: 'Engineering',
    teamId: 'team-3',
    teamName: 'Infrastructure & SRE',
    managerId: 'usr-9',
    managerName: 'Liam O’Connor',
    attendanceStatus: 'WORKING',
    lastActiveAt: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
    joinedAt: '2023-05-01T00:00:00Z',
    location: 'Melbourne, AU',
    timezone: 'AEST (UTC+10)',
    skills: ['AWS', 'GCP', 'Multi-region', 'Cost Optimization'],
    leaveBalance: { casualTotal: 12, casualUsed: 3, sickTotal: 10, sickUsed: 0, annualTotal: 18, annualUsed: 8 },
  },
  {
    id: 'usr-20',
    name: 'Fatima Zahra',
    email: 'fatima.zahra@workpulse.io',
    avatarUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=150&auto=format&fit=crop&q=80',
    jobTitle: 'HR Operations Specialist',
    role: 'HR',
    departmentId: 'dept-5',
    departmentName: 'People & Culture',
    teamId: 'team-8',
    teamName: 'People Ops & HR',
    managerId: 'usr-8',
    managerName: 'Rachel Vance',
    attendanceStatus: 'WORKING',
    lastActiveAt: new Date(Date.now() - 11 * 60 * 1000).toISOString(),
    joinedAt: '2023-07-15T00:00:00Z',
    location: 'London, UK',
    timezone: 'GMT (UTC+0)',
    skills: ['Onboarding', 'Payroll Sync', 'Benefits', 'HRIS'],
    leaveBalance: { casualTotal: 12, casualUsed: 1, sickTotal: 10, sickUsed: 1, annualTotal: 18, annualUsed: 2 },
  },
  {
    id: 'usr-21',
    name: 'Daniel Kim',
    email: 'daniel.kim@workpulse.io',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    jobTitle: 'Junior Frontend Developer',
    role: 'EMPLOYEE',
    departmentId: 'dept-1',
    departmentName: 'Engineering',
    teamId: 'team-1',
    teamName: 'Frontend Core',
    managerId: 'usr-7',
    managerName: 'Marcus Wright',
    attendanceStatus: 'LATE',
    lastActiveAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    joinedAt: '2024-01-10T00:00:00Z',
    location: 'Seoul, KR',
    timezone: 'KST (UTC+9)',
    skills: ['HTML/CSS', 'JavaScript', 'React', 'Tailwind'],
    leaveBalance: { casualTotal: 12, casualUsed: 1, sickTotal: 10, sickUsed: 0, annualTotal: 18, annualUsed: 2 },
  },
  {
    id: 'usr-22',
    name: 'Hannah Scott',
    email: 'hannah.scott@workpulse.io',
    avatarUrl: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=150&auto=format&fit=crop&q=80',
    jobTitle: 'Data Engineer',
    role: 'EMPLOYEE',
    departmentId: 'dept-1',
    departmentName: 'Engineering',
    teamId: 'team-2',
    teamName: 'Backend & Platform',
    managerId: 'usr-2',
    managerName: 'Vikram Mehta',
    attendanceStatus: 'WORKING',
    lastActiveAt: new Date(Date.now() - 17 * 60 * 1000).toISOString(),
    joinedAt: '2023-08-20T00:00:00Z',
    location: 'Boston, US',
    timezone: 'EST (UTC-5)',
    skills: ['Apache Spark', 'Snowflake', 'dbt', 'Python'],
    leaveBalance: { casualTotal: 12, casualUsed: 2, sickTotal: 10, sickUsed: 0, annualTotal: 18, annualUsed: 5 },
  },
  {
    id: 'usr-23',
    name: 'Tariq Hassan',
    email: 'tariq.hassan@workpulse.io',
    avatarUrl: 'https://images.unsplash.com/photo-1513956589380-bad6acb9b9d4?w=150&auto=format&fit=crop&q=80',
    jobTitle: 'Performance Marketing Manager',
    role: 'EMPLOYEE',
    departmentId: 'dept-3',
    departmentName: 'Marketing & Growth',
    teamId: 'team-6',
    teamName: 'Growth Marketing',
    managerId: 'usr-10',
    managerName: 'Elena Rostova',
    attendanceStatus: 'WORKING',
    lastActiveAt: new Date(Date.now() - 22 * 60 * 1000).toISOString(),
    joinedAt: '2023-09-10T00:00:00Z',
    location: 'Cairo, EG',
    timezone: 'EET (UTC+2)',
    skills: ['Google Ads', 'LinkedIn Ads', 'Funnel Analytics', 'A/B Testing'],
    leaveBalance: { casualTotal: 12, casualUsed: 3, sickTotal: 10, sickUsed: 1, annualTotal: 18, annualUsed: 4 },
  },
  {
    id: 'usr-24',
    name: 'Emily Watson',
    email: 'emily.watson@workpulse.io',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    jobTitle: 'UI/UX Researcher',
    role: 'EMPLOYEE',
    departmentId: 'dept-2',
    departmentName: 'Product & Design',
    teamId: 'team-5',
    teamName: 'Product Design',
    managerId: 'usr-15',
    managerName: 'Siddharth Rao',
    attendanceStatus: 'WORKING',
    lastActiveAt: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
    joinedAt: '2023-10-01T00:00:00Z',
    location: 'Vancouver, CA',
    timezone: 'PST (UTC-8)',
    skills: ['User Interviews', 'Usability Testing', 'Persona Mapping'],
    leaveBalance: { casualTotal: 12, casualUsed: 1, sickTotal: 10, sickUsed: 0, annualTotal: 18, annualUsed: 3 },
  },
  {
    id: 'usr-25',
    name: 'Gabriel Rossi',
    email: 'gabriel.rossi@workpulse.io',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    jobTitle: 'Backend Security Engineer',
    role: 'EMPLOYEE',
    departmentId: 'dept-4',
    departmentName: 'Operations & SecOps',
    teamId: 'team-7',
    teamName: 'Operations & IT',
    managerId: 'usr-11',
    managerName: 'David Chen',
    attendanceStatus: 'WORKING',
    lastActiveAt: new Date(Date.now() - 19 * 60 * 1000).toISOString(),
    joinedAt: '2023-11-01T00:00:00Z',
    location: 'Rome, IT',
    timezone: 'CET (UTC+1)',
    skills: ['Cryptography', 'OAuth2', 'Zero Trust', 'Linux'],
    leaveBalance: { casualTotal: 12, casualUsed: 2, sickTotal: 10, sickUsed: 1, annualTotal: 18, annualUsed: 5 },
  },
];

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'proj-1',
    name: 'Project Phoenix - Core Cloud Platform V2',
    code: 'PHX',
    description: 'Next-gen distributed cloud infrastructure and microservice mesh for high availability.',
    status: 'Active',
    health: 'At Risk',
    progress: 68,
    departmentId: 'dept-1',
    teamId: 'team-2',
    leadId: 'usr-2',
    leadName: 'Vikram Mehta',
    startDate: '2026-06-01T00:00:00Z',
    targetDate: '2026-10-15T00:00:00Z',
    totalTasks: 24,
    completedTasks: 16,
    blockedTasks: 2,
    inProgressTasks: 6,
    milestones: [
      { id: 'm-1', title: 'Data Schema Migration', projectId: 'proj-1', dueDate: '2026-07-15T00:00:00Z', isCompleted: true, progress: 100, taskCount: 8, completedTaskCount: 8 },
      { id: 'm-2', title: 'Service Mesh & Distributed Tracing', projectId: 'proj-1', dueDate: '2026-09-15T00:00:00Z', isCompleted: false, progress: 65, taskCount: 10, completedTaskCount: 6 },
      { id: 'm-3', title: 'Production Cutover & Chaos Testing', projectId: 'proj-1', dueDate: '2026-10-15T00:00:00Z', isCompleted: false, progress: 20, taskCount: 6, completedTaskCount: 2 },
    ],
  },
  {
    id: 'proj-2',
    name: 'Odyssey - Modern Design System 2.0',
    code: 'ODY',
    description: 'Unified component library, design tokens, accessible primitives, and fluid micro-interactions.',
    status: 'Active',
    health: 'On Track',
    progress: 82,
    departmentId: 'dept-2',
    teamId: 'team-5',
    leadId: 'usr-15',
    leadName: 'Siddharth Rao',
    startDate: '2026-05-15T00:00:00Z',
    targetDate: '2026-09-30T00:00:00Z',
    totalTasks: 18,
    completedTasks: 15,
    blockedTasks: 0,
    inProgressTasks: 3,
    milestones: [
      { id: 'm-4', title: 'Figma Token Sync & Variables', projectId: 'proj-2', dueDate: '2026-06-30T00:00:00Z', isCompleted: true, progress: 100, taskCount: 6, completedTaskCount: 6 },
      { id: 'm-5', title: 'Core React Primitives & Motion', projectId: 'proj-2', dueDate: '2026-08-31T00:00:00Z', isCompleted: true, progress: 100, taskCount: 7, completedTaskCount: 7 },
      { id: 'm-6', title: 'Documentation & Storybook QA', projectId: 'proj-2', dueDate: '2026-09-30T00:00:00Z', isCompleted: false, progress: 40, taskCount: 5, completedTaskCount: 2 },
    ],
  },
  {
    id: 'proj-3',
    name: 'Helix - Realtime Event Pipeline',
    code: 'HLX',
    description: 'Kafka + ClickHouse analytics pipeline processing 50k events/sec with sub-second latency.',
    status: 'Active',
    health: 'On Track',
    progress: 74,
    departmentId: 'dept-1',
    teamId: 'team-2',
    leadId: 'usr-4',
    leadName: 'Priya Patel',
    startDate: '2026-07-01T00:00:00Z',
    targetDate: '2026-11-01T00:00:00Z',
    totalTasks: 16,
    completedTasks: 12,
    blockedTasks: 1,
    inProgressTasks: 3,
    milestones: [
      { id: 'm-7', title: 'Ingestion Cluster Setup', projectId: 'proj-3', dueDate: '2026-08-15T00:00:00Z', isCompleted: true, progress: 100, taskCount: 6, completedTaskCount: 6 },
      { id: 'm-8', title: 'Aggregator & Rollup Engine', projectId: 'proj-3', dueDate: '2026-09-30T00:00:00Z', isCompleted: false, progress: 70, taskCount: 6, completedTaskCount: 4 },
      { id: 'm-9', title: 'Client SDKs & Webhooks', projectId: 'proj-3', dueDate: '2026-11-01T00:00:00Z', isCompleted: false, progress: 30, taskCount: 4, completedTaskCount: 2 },
    ],
  },
  {
    id: 'proj-4',
    name: 'Horizon - Enterprise Auth & Role Policies',
    code: 'HRZ',
    description: 'SAML 2.0, Okta/Azure SSO, SCIM provisioning, and granular RBAC permission matrix.',
    status: 'Active',
    health: 'On Track',
    progress: 90,
    departmentId: 'dept-1',
    teamId: 'team-1',
    leadId: 'usr-3',
    leadName: 'Rahul Sharma',
    startDate: '2026-06-15T00:00:00Z',
    targetDate: '2026-09-20T00:00:00Z',
    totalTasks: 14,
    completedTasks: 13,
    blockedTasks: 0,
    inProgressTasks: 1,
    milestones: [
      { id: 'm-10', title: 'SAML & OIDC Engine', projectId: 'proj-4', dueDate: '2026-07-30T00:00:00Z', isCompleted: true, progress: 100, taskCount: 5, completedTaskCount: 5 },
      { id: 'm-11', title: 'SCIM Directory Sync', projectId: 'proj-4', dueDate: '2026-08-31T00:00:00Z', isCompleted: true, progress: 100, taskCount: 5, completedTaskCount: 5 },
      { id: 'm-12', title: 'Security Audit & Pen Test', projectId: 'proj-4', dueDate: '2026-09-20T00:00:00Z', isCompleted: false, progress: 75, taskCount: 4, completedTaskCount: 3 },
    ],
  },
  {
    id: 'proj-5',
    name: 'Aegis - SOC2 Type II & Security Compliance Suite',
    code: 'AGS',
    description: 'Continuous compliance monitoring, automated evidence collection, and vulnerability scanning.',
    status: 'Active',
    health: 'On Track',
    progress: 60,
    departmentId: 'dept-4',
    teamId: 'team-7',
    leadId: 'usr-11',
    leadName: 'David Chen',
    startDate: '2026-07-15T00:00:00Z',
    targetDate: '2026-11-30T00:00:00Z',
    totalTasks: 20,
    completedTasks: 12,
    blockedTasks: 0,
    inProgressTasks: 8,
    milestones: [
      { id: 'm-13', title: 'Access Control Policies', projectId: 'proj-5', dueDate: '2026-08-30T00:00:00Z', isCompleted: true, progress: 100, taskCount: 7, completedTaskCount: 7 },
      { id: 'm-14', title: 'Automated Audit Trails', projectId: 'proj-5', dueDate: '2026-10-15T00:00:00Z', isCompleted: false, progress: 50, taskCount: 8, completedTaskCount: 4 },
      { id: 'm-15', title: 'Final Auditor Certification', projectId: 'proj-5', dueDate: '2026-11-30T00:00:00Z', isCompleted: false, progress: 10, taskCount: 5, completedTaskCount: 1 },
    ],
  },
];

export const INITIAL_BLOCKERS: Blocker[] = [
  {
    id: 'blk-1',
    title: 'AWS KMS Key Access Policy Mismatch',
    description: 'Platform microservices cannot decrypt cross-region secrets due to missing IAM role delegation from SecOps.',
    severity: 'HIGH',
    status: 'OPEN',
    taskId: 'tsk-3',
    taskTitle: 'Cross-Region Secret Replication',
    projectId: 'proj-1',
    projectName: 'Project Phoenix - Core Cloud Platform V2',
    reporterId: 'usr-4',
    reporterName: 'Priya Patel',
    reporterAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    dependencyOwnerId: 'usr-11',
    dependencyOwnerName: 'David Chen',
    reportedAt: new Date(Date.now() - 52 * 60 * 60 * 1000).toISOString(), // 52h ago
    expectedResolution: new Date(Date.now() + 12 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'blk-2',
    title: 'Kafka Partitions Rebalancing Throttling',
    description: 'Consumer group lag spiking on real-time event pipeline due to consumer timeout configurations.',
    severity: 'CRITICAL',
    status: 'IN_PROGRESS',
    taskId: 'tsk-7',
    taskTitle: 'Aggregator Lag Reduction & Autoscaling',
    projectId: 'proj-3',
    projectName: 'Helix - Realtime Event Pipeline',
    reporterId: 'usr-4',
    reporterName: 'Priya Patel',
    reporterAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    dependencyOwnerId: 'usr-9',
    dependencyOwnerName: 'Liam O’Connor',
    resolverId: 'usr-9',
    resolverName: 'Liam O’Connor',
    reportedAt: new Date(Date.now() - 28 * 60 * 60 * 1000).toISOString(),
    expectedResolution: new Date(Date.now() + 6 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'blk-3',
    title: 'Design Token Export Missing iOS Format',
    description: 'Mobile team is blocked on token sync because Style Dictionary config is missing SwiftUI Color asset exporter.',
    severity: 'MEDIUM',
    status: 'ACKNOWLEDGED',
    taskId: 'tsk-12',
    taskTitle: 'Multi-platform Token Exporter Pipeline',
    projectId: 'proj-2',
    projectName: 'Odyssey - Modern Design System 2.0',
    reporterId: 'usr-6',
    reporterName: 'Ananya Iyer',
    reporterAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    dependencyOwnerId: 'usr-15',
    dependencyOwnerName: 'Siddharth Rao',
    reportedAt: new Date(Date.now() - 14 * 60 * 60 * 1000).toISOString(),
    expectedResolution: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const INITIAL_TASKS: Task[] = [
  {
    id: 'tsk-1',
    title: 'Implement Multi-Region Redis Cache Failover',
    description: 'Configure automated Sentinel and cluster cross-region replication for zero-downtime failover.',
    projectId: 'proj-1',
    projectName: 'Project Phoenix - Core Cloud Platform V2',
    milestoneId: 'm-2',
    milestoneName: 'Service Mesh & Distributed Tracing',
    assigneeId: 'usr-2',
    assigneeName: 'Vikram Mehta',
    assigneeAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    creatorId: 'usr-1',
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    progress: 75,
    dueDate: '2026-09-15T00:00:00Z',
    estimatedHours: 24,
    loggedHours: 18,
    subtasks: [
      { id: 'sub-1', title: 'Write failover benchmark tests', isCompleted: true },
      { id: 'sub-2', title: 'Configure Envoy proxy retry policies', isCompleted: true },
      { id: 'sub-3', title: 'Test latency degradation during switch', isCompleted: false },
    ],
    blockerIds: [],
    comments: [
      {
        id: 'c-1',
        authorId: 'usr-1',
        authorName: 'Sarah Jenkins',
        authorAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
        content: 'Looks solid Vikram. Let’s run the staging chaos drill on Thursday.',
        createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
      },
    ],
    tags: ['Backend', 'Infrastructure', 'Redis'],
    createdAt: '2026-08-20T00:00:00Z',
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'tsk-2',
    title: 'Audit and Refactor Legacy SQL Joins in Billing',
    description: 'Optimize N+1 query patterns in monthly invoice generation service to reduce DB CPU spike from 85% to <25%.',
    projectId: 'proj-1',
    projectName: 'Project Phoenix - Core Cloud Platform V2',
    milestoneId: 'm-2',
    milestoneName: 'Service Mesh & Distributed Tracing',
    assigneeId: 'usr-3',
    assigneeName: 'Rahul Sharma',
    assigneeAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    creatorId: 'usr-2',
    status: 'IN_PROGRESS',
    priority: 'MEDIUM',
    progress: 60,
    dueDate: '2026-09-12T00:00:00Z',
    estimatedHours: 20,
    loggedHours: 12,
    subtasks: [
      { id: 'sub-4', title: 'Profile slow queries via pg_stat_statements', isCompleted: true },
      { id: 'sub-5', title: 'Add composite index on (tenant_id, billing_cycle)', isCompleted: true },
      { id: 'sub-6', title: 'Benchmark with 100k test invoices', isCompleted: false },
    ],
    blockerIds: [],
    comments: [],
    tags: ['Database', 'PostgreSQL', 'Performance'],
    createdAt: '2026-08-25T00:00:00Z',
    updatedAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'tsk-3',
    title: 'Cross-Region Secret Replication & KMS Integration',
    description: 'Enable automated secret synchronization across us-east-1 and eu-west-1 regions.',
    projectId: 'proj-1',
    projectName: 'Project Phoenix - Core Cloud Platform V2',
    milestoneId: 'm-2',
    milestoneName: 'Service Mesh & Distributed Tracing',
    assigneeId: 'usr-4',
    assigneeName: 'Priya Patel',
    assigneeAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    creatorId: 'usr-2',
    status: 'BLOCKED',
    priority: 'CRITICAL',
    progress: 40,
    dueDate: '2026-09-10T00:00:00Z',
    estimatedHours: 16,
    loggedHours: 7,
    subtasks: [
      { id: 'sub-7', title: 'Set up KMS key replica policy', isCompleted: true },
      { id: 'sub-8', title: 'Configure IAM role assume trust with SecOps', isCompleted: false },
      { id: 'sub-9', title: 'Deploy HashiCorp Vault secrets engine sync', isCompleted: false },
    ],
    blockerIds: ['blk-1'],
    comments: [
      {
        id: 'c-2',
        authorId: 'usr-4',
        authorName: 'Priya Patel',
        authorAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
        content: 'Blocked on David Chen’s team granting IAM role delegation on the target account.',
        createdAt: new Date(Date.now() - 50 * 60 * 60 * 1000).toISOString(),
      },
    ],
    tags: ['Security', 'KMS', 'AWS', 'Blocked'],
    createdAt: '2026-08-28T00:00:00Z',
    updatedAt: new Date(Date.now() - 52 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'tsk-4',
    title: 'Build Interactive Data Visualization Widgets for Dashboards',
    description: 'Create fluid Recharts wrapper components with dynamic dark-mode tooltips, brush controls, and SVG animations.',
    projectId: 'proj-2',
    projectName: 'Odyssey - Modern Design System 2.0',
    milestoneId: 'm-5',
    milestoneName: 'Core React Primitives & Motion',
    assigneeId: 'usr-6',
    assigneeName: 'Ananya Iyer',
    assigneeAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    creatorId: 'usr-15',
    status: 'COMPLETED',
    priority: 'HIGH',
    progress: 100,
    dueDate: '2026-09-05T00:00:00Z',
    estimatedHours: 32,
    loggedHours: 30,
    subtasks: [
      { id: 'sub-10', title: 'Bar and Line chart themes', isCompleted: true },
      { id: 'sub-11', title: 'Donut & Progress ring animations', isCompleted: true },
      { id: 'sub-12', title: 'Accessibility aria-labels and keyboard navigation', isCompleted: true },
    ],
    blockerIds: [],
    comments: [],
    tags: ['Design System', 'Charts', 'React', 'A11y'],
    createdAt: '2026-08-15T00:00:00Z',
    updatedAt: new Date(Date.now() - 36 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'tsk-5',
    title: 'Framer Motion Command Palette & Micro-Interactions',
    description: 'Implement sleek Cmd+K modal with spring animations, fuzzy search, and keyboard shortcuts.',
    projectId: 'proj-2',
    projectName: 'Odyssey - Modern Design System 2.0',
    milestoneId: 'm-5',
    milestoneName: 'Core React Primitives & Motion',
    assigneeId: 'usr-12',
    assigneeName: 'Kavita Nair',
    assigneeAvatar: 'https://images.unsplash.com/photo-1534751516642-a171edd2521d?w=150&auto=format&fit=crop&q=80',
    creatorId: 'usr-7',
    status: 'IN_PROGRESS',
    priority: 'MEDIUM',
    progress: 85,
    dueDate: '2026-09-10T00:00:00Z',
    estimatedHours: 18,
    loggedHours: 15,
    subtasks: [
      { id: 'sub-13', title: 'Command modal backdrop and container', isCompleted: true },
      { id: 'sub-14', title: 'Fuzzy search query ranking', isCompleted: true },
      { id: 'sub-15', title: 'Category grouping & recent search history', isCompleted: true },
      { id: 'sub-16', title: 'Keyboard arrow navigation edge cases', isCompleted: false },
    ],
    blockerIds: [],
    comments: [],
    tags: ['UI', 'Framer Motion', 'Search'],
    createdAt: '2026-08-28T00:00:00Z',
    updatedAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'tsk-6',
    title: 'Design System Documentation Site & Storybook Deploy',
    description: 'Publish full component API documentation, code snippet copy buttons, and interactive playground.',
    projectId: 'proj-2',
    projectName: 'Odyssey - Modern Design System 2.0',
    milestoneId: 'm-6',
    milestoneName: 'Documentation & Storybook QA',
    assigneeId: 'usr-6',
    assigneeName: 'Ananya Iyer',
    assigneeAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    creatorId: 'usr-15',
    status: 'IN_PROGRESS',
    priority: 'MEDIUM',
    progress: 40,
    dueDate: '2026-09-18T00:00:00Z',
    estimatedHours: 24,
    loggedHours: 10,
    subtasks: [
      { id: 'sub-17', title: 'Docsite layout with search', isCompleted: true },
      { id: 'sub-18', title: 'Component props table generation', isCompleted: false },
      { id: 'sub-19', title: 'Color palette previewer with copy HEX/HSL', isCompleted: true },
    ],
    blockerIds: [],
    comments: [],
    tags: ['Documentation', 'Storybook', 'Design'],
    createdAt: '2026-08-30T00:00:00Z',
    updatedAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'tsk-7',
    title: 'Aggregator Lag Reduction & Autoscaling in ClickHouse Pipeline',
    description: 'Optimize ClickHouse buffer tables and tune Kafka consumer batch size to prevent consumer lag under spike load.',
    projectId: 'proj-3',
    projectName: 'Helix - Realtime Event Pipeline',
    milestoneId: 'm-8',
    milestoneName: 'Aggregator & Rollup Engine',
    assigneeId: 'usr-4',
    assigneeName: 'Priya Patel',
    assigneeAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    creatorId: 'usr-2',
    status: 'BLOCKED',
    priority: 'HIGH',
    progress: 55,
    dueDate: '2026-09-14T00:00:00Z',
    estimatedHours: 28,
    loggedHours: 16,
    subtasks: [
      { id: 'sub-20', title: 'Tune ClickHouse max_insert_block_size', isCompleted: true },
      { id: 'sub-21', title: 'Configure KEDA HPA on consumer pods', isCompleted: false },
      { id: 'sub-22', title: 'Benchmark consumer lag during synthetic 60k req/s load test', isCompleted: false },
    ],
    blockerIds: ['blk-2'],
    comments: [],
    tags: ['ClickHouse', 'Kafka', 'Performance', 'Blocked'],
    createdAt: '2026-08-22T00:00:00Z',
    updatedAt: new Date(Date.now() - 28 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'tsk-8',
    title: 'SCIM 2.0 User Provisioning & Deprovisioning Webhooks',
    description: 'Implement standard SCIM endpoints (/Users, /Groups) to support automated sync from Okta and Azure AD.',
    projectId: 'proj-4',
    projectName: 'Horizon - Enterprise Auth & Role Policies',
    milestoneId: 'm-11',
    milestoneName: 'SCIM Directory Sync',
    assigneeId: 'usr-3',
    assigneeName: 'Rahul Sharma',
    assigneeAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    creatorId: 'usr-1',
    status: 'COMPLETED',
    priority: 'HIGH',
    progress: 100,
    dueDate: '2026-08-30T00:00:00Z',
    estimatedHours: 35,
    loggedHours: 34,
    subtasks: [
      { id: 'sub-23', title: 'GET /Users pagination & filter parser', isCompleted: true },
      { id: 'sub-24', title: 'PATCH /Users attributes update', isCompleted: true },
      { id: 'sub-25', title: 'DELETE /Users soft-deactivation logic', isCompleted: true },
      { id: 'sub-26', title: 'Okta SCIM test suite compliance pass', isCompleted: true },
    ],
    blockerIds: [],
    comments: [],
    tags: ['Auth', 'SCIM', 'Enterprise', 'Okta'],
    createdAt: '2026-08-10T00:00:00Z',
    updatedAt: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'tsk-9',
    title: 'Penetration Testing Remediations for Horizon Auth Gateway',
    description: 'Resolve external audit findings: enforce PKCE for all OAuth2 flows, tighten CORS on token endpoints, and add rate-limiting.',
    projectId: 'proj-4',
    projectName: 'Horizon - Enterprise Auth & Role Policies',
    milestoneId: 'm-12',
    milestoneName: 'Security Audit & Pen Test',
    assigneeId: 'usr-3',
    assigneeName: 'Rahul Sharma',
    assigneeAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    creatorId: 'usr-11',
    status: 'REVIEW',
    priority: 'CRITICAL',
    progress: 90,
    dueDate: '2026-09-11T00:00:00Z',
    estimatedHours: 20,
    loggedHours: 18,
    subtasks: [
      { id: 'sub-27', title: 'Mandate PKCE code_challenge verification', isCompleted: true },
      { id: 'sub-28', title: 'Restrict CORS headers strictly to verified client origins', isCompleted: true },
      { id: 'sub-29', title: 'Redis token endpoint rate limiter (10 req/min/IP)', isCompleted: true },
    ],
    blockerIds: [],
    comments: [
      {
        id: 'c-3',
        authorId: 'usr-16',
        authorName: 'Aisha Al-Mansoor',
        authorAvatar: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=150&auto=format&fit=crop&q=80',
        content: 'Verification script passed for PKCE. Reviewing rate-limiting headers now.',
        createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
      },
    ],
    tags: ['Security', 'Auth', 'PenTest', 'Review'],
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'tsk-10',
    title: 'Automate SOC2 Evidence Collection for AWS CloudTrail & GuardDuty',
    description: 'Deploy scheduled Lambda functions and audit scripts that verify continuous encryption, logging retention, and MFA enforcement.',
    projectId: 'proj-5',
    projectName: 'Aegis - SOC2 Type II & Security Compliance Suite',
    milestoneId: 'm-14',
    milestoneName: 'Automated Audit Trails',
    assigneeId: 'usr-16',
    assigneeName: 'Aisha Al-Mansoor',
    assigneeAvatar: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=150&auto=format&fit=crop&q=80',
    creatorId: 'usr-11',
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    progress: 50,
    dueDate: '2026-09-25T00:00:00Z',
    estimatedHours: 30,
    loggedHours: 15,
    subtasks: [
      { id: 'sub-30', title: 'CloudTrail log integrity validation', isCompleted: true },
      { id: 'sub-31', title: 'S3 bucket policy automated inspector', isCompleted: true },
      { id: 'sub-32', title: 'Vanta API integration for auto-uploading evidence', isCompleted: false },
    ],
    blockerIds: [],
    comments: [],
    tags: ['Security', 'Compliance', 'SOC2', 'AWS'],
    createdAt: '2026-08-25T00:00:00Z',
    updatedAt: new Date(Date.now() - 16 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'tsk-11',
    title: 'Cross-Browser Playwright E2E Test Suite for WorkPulse Core',
    description: 'Author automated end-to-end tests for all critical user workflows: check-in, blocker reporting, leave approval, and search.',
    projectId: 'proj-1',
    projectName: 'Project Phoenix - Core Cloud Platform V2',
    milestoneId: 'm-3',
    milestoneName: 'Production Cutover & Chaos Testing',
    assigneeId: 'usr-17',
    assigneeName: 'Lucas Silva',
    assigneeAvatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    creatorId: 'usr-7',
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    progress: 45,
    dueDate: '2026-09-19T00:00:00Z',
    estimatedHours: 24,
    loggedHours: 11,
    subtasks: [
      { id: 'sub-33', title: 'Dashboard attention item interaction flow', isCompleted: true },
      { id: 'sub-34', title: 'Leave request submission with workload intelligence preview', isCompleted: true },
      { id: 'sub-35', title: 'Missed meeting explanation and manager triage test', isCompleted: false },
    ],
    blockerIds: [],
    comments: [],
    tags: ['QA', 'E2E', 'Testing', 'Playwright'],
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'tsk-12',
    title: 'Multi-platform Token Exporter Pipeline for Design Tokens',
    description: 'Transform Figma JSON tokens into CSS variables, SCSS maps, Tailwind config, and Swift Color assets.',
    projectId: 'proj-2',
    projectName: 'Odyssey - Modern Design System 2.0',
    milestoneId: 'm-6',
    milestoneName: 'Documentation & Storybook QA',
    assigneeId: 'usr-6',
    assigneeName: 'Ananya Iyer',
    assigneeAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    creatorId: 'usr-15',
    status: 'BLOCKED',
    priority: 'MEDIUM',
    progress: 30,
    dueDate: '2026-09-15T00:00:00Z',
    estimatedHours: 16,
    loggedHours: 5,
    subtasks: [
      { id: 'sub-36', title: 'Style Dictionary core configuration', isCompleted: true },
      { id: 'sub-37', title: 'Swift asset catalog custom formatter', isCompleted: false },
      { id: 'sub-38', title: 'CI action to trigger token publish on tag', isCompleted: false },
    ],
    blockerIds: ['blk-3'],
    comments: [],
    tags: ['Design System', 'Tokens', 'Figma', 'Blocked'],
    createdAt: '2026-08-29T00:00:00Z',
    updatedAt: new Date(Date.now() - 14 * 60 * 60 * 1000).toISOString(),
  },
];

export const INITIAL_MEETINGS: Meeting[] = [
  {
    id: 'mtg-1',
    title: 'Engineering Daily Standup & Blocker Triage',
    description: 'Daily sync on active project blockers, cross-team dependencies, and code reviews.',
    agenda: '1. Blocker updates (Phoenix & Helix)\n2. Deployment status\n3. PR reviews needing attention',
    meetingUrl: 'https://meet.google.com/wp-eng-daily',
    scheduledAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(), // 3h ago today
    durationMins: 25,
    organizerId: 'usr-1',
    organizerName: 'Sarah Jenkins',
    departmentId: 'dept-1',
    teamId: 'team-1',
    status: 'Completed',
    attendances: [
      {
        id: 'att-1',
        meetingId: 'mtg-1',
        userId: 'usr-1',
        userName: 'Sarah Jenkins',
        userAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
        userRole: 'VP of Engineering',
        status: 'PRESENT',
        joinedAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
        isManagerExcused: false,
        updatedAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: 'att-2',
        meetingId: 'mtg-1',
        userId: 'usr-2',
        userName: 'Vikram Mehta',
        userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
        userRole: 'Engineering Manager',
        status: 'PRESENT',
        joinedAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
        isManagerExcused: false,
        updatedAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: 'att-3',
        meetingId: 'mtg-1',
        userId: 'usr-3',
        userName: 'Rahul Sharma',
        userAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
        userRole: 'Senior Fullstack Engineer',
        status: 'ABSENT',
        missedReason: 'TECHNICAL_ISSUE',
        explanationNote: 'ISP fiber cut in neighborhood from 9:30am to 10:45am. Back online via backup hotspot now.',
        isManagerExcused: false, // Needs Manager Action!
        updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: 'att-4',
        meetingId: 'mtg-1',
        userId: 'usr-4',
        userName: 'Priya Patel',
        userAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
        userRole: 'Staff Backend Engineer',
        status: 'PRESENT',
        joinedAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
        isManagerExcused: false,
        updatedAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: 'att-5',
        meetingId: 'mtg-1',
        userId: 'usr-7',
        userName: 'Marcus Wright',
        userAvatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
        userRole: 'Frontend Lead',
        status: 'PRESENT',
        joinedAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
        isManagerExcused: false,
        updatedAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: 'att-6',
        meetingId: 'mtg-1',
        userId: 'usr-21',
        userName: 'Daniel Kim',
        userAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
        userRole: 'Junior Frontend Developer',
        status: 'LATE',
        joinedAt: new Date(Date.now() - 2 * 60 * 60 * 1000 - 45 * 60 * 1000).toISOString(),
        missedReason: 'WORK_CONFLICT',
        explanationNote: 'Was troubleshooting urgent staging login glitch.',
        isManagerExcused: true,
        actionTaken: 'Accepted',
        updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
      },
    ],
  },
  {
    id: 'mtg-2',
    title: 'Project Phoenix Architecture Review & Security Gate',
    description: 'Weekly deep-dive on cloud topology, zero-trust IAM policies, and cross-region latency testing.',
    agenda: '1. Review KMS IAM permission blocker\n2. Service mesh Envoy proxy timeouts\n3. Staging disaster recovery dry run',
    meetingUrl: 'https://meet.google.com/wp-phx-arch',
    scheduledAt: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(), // 4h in future today
    durationMins: 45,
    organizerId: 'usr-2',
    organizerName: 'Vikram Mehta',
    departmentId: 'dept-1',
    status: 'Scheduled',
    attendances: [
      {
        id: 'att-7',
        meetingId: 'mtg-2',
        userId: 'usr-2',
        userName: 'Vikram Mehta',
        userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
        userRole: 'Engineering Manager',
        status: 'PRESENT',
        isManagerExcused: false,
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'att-8',
        meetingId: 'mtg-2',
        userId: 'usr-4',
        userName: 'Priya Patel',
        userAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
        userRole: 'Staff Backend Engineer',
        status: 'PRESENT',
        isManagerExcused: false,
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'att-9',
        meetingId: 'mtg-2',
        userId: 'usr-9',
        userName: 'Liam O’Connor',
        userAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
        userRole: 'Lead SRE',
        status: 'PRESENT',
        isManagerExcused: false,
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'att-10',
        meetingId: 'mtg-2',
        userId: 'usr-11',
        userName: 'David Chen',
        userAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
        userRole: 'Head of Operations',
        status: 'PRESENT',
        isManagerExcused: false,
        updatedAt: new Date().toISOString(),
      },
    ],
  },
  {
    id: 'mtg-3',
    title: 'Product & Design Weekly Sync',
    description: 'Reviewing Odyssey component specs, user research insights from Enterprise clients, and Q4 roadmap.',
    agenda: '1. Usability test highlights on WorkPulse Dashboard\n2. Odyssey Figma variables handover\n3. Design token SwiftUI export timeline',
    meetingUrl: 'https://meet.google.com/wp-prod-design',
    scheduledAt: new Date(Date.now() + 6 * 60 * 60 * 1000).toISOString(),
    durationMins: 50,
    organizerId: 'usr-5',
    organizerName: 'Alex Rivera',
    departmentId: 'dept-2',
    status: 'Scheduled',
    attendances: [
      {
        id: 'att-11',
        meetingId: 'mtg-3',
        userId: 'usr-5',
        userName: 'Alex Rivera',
        userAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
        userRole: 'Head of Product',
        status: 'PRESENT',
        isManagerExcused: false,
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'att-12',
        meetingId: 'mtg-3',
        userId: 'usr-6',
        userName: 'Ananya Iyer',
        userAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
        userRole: 'Senior Product Designer',
        status: 'PRESENT',
        isManagerExcused: false,
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'att-13',
        meetingId: 'mtg-3',
        userId: 'usr-14',
        userName: 'Zoe Dubois',
        userAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
        userRole: 'Product Manager',
        status: 'PRESENT',
        isManagerExcused: false,
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'att-14',
        meetingId: 'mtg-3',
        userId: 'usr-15',
        userName: 'Siddharth Rao',
        userAvatar: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=150&auto=format&fit=crop&q=80',
        userRole: 'Design Lead',
        status: 'PRESENT',
        isManagerExcused: false,
        updatedAt: new Date().toISOString(),
      },
    ],
  },
];

export const INITIAL_LEAVES: LeaveRequest[] = [
  {
    id: 'lev-1',
    userId: 'usr-6',
    userName: 'Ananya Iyer',
    userAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    userJobTitle: 'Senior Product Designer',
    departmentName: 'Product & Design',
    leaveType: 'ANNUAL',
    startDate: '2026-09-14T00:00:00Z',
    endDate: '2026-09-16T00:00:00Z',
    isHalfDay: false,
    totalDays: 3,
    reason: 'Family wedding and travel out of town.',
    handoverCompleted: true,
    handoverNotes: 'Completed Figma component specs for Token Exporter. Siddharth Rao has full write permissions on project file and will review mobile QA.',
    backupUserId: 'usr-15',
    backupUserName: 'Siddharth Rao',
    status: 'PENDING_APPROVAL', // Pending Manager Action!
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'lev-2',
    userId: 'usr-13',
    userName: 'Carlos Mendez',
    userAvatar: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=150&auto=format&fit=crop&q=80',
    userJobTitle: 'Senior Backend Engineer',
    departmentName: 'Engineering',
    leaveType: 'CASUAL',
    startDate: '2026-09-07T00:00:00Z',
    endDate: '2026-09-09T00:00:00Z',
    isHalfDay: false,
    totalDays: 3,
    reason: 'Personal time off for medical checkup.',
    handoverCompleted: true,
    handoverNotes: 'All ongoing PRs merged into development branch. Vikram Mehta handling urgent platform escalations.',
    backupUserId: 'usr-2',
    backupUserName: 'Vikram Mehta',
    status: 'APPROVED',
    approverId: 'usr-2',
    approverName: 'Vikram Mehta',
    decisionNotes: 'Approved. Thanks for having all PRs merged ahead of time.',
    decisionAt: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    createdAt: '2026-09-02T00:00:00Z',
  },
  {
    id: 'lev-3',
    userId: 'usr-3',
    userName: 'Rahul Sharma',
    userAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    userJobTitle: 'Senior Fullstack Engineer',
    departmentName: 'Engineering',
    leaveType: 'WORK_FROM_HOME',
    startDate: '2026-09-18T00:00:00Z',
    endDate: '2026-09-18T00:00:00Z',
    isHalfDay: false,
    totalDays: 1,
    reason: 'Home maintenance work.',
    handoverCompleted: true,
    handoverNotes: 'Will be active on Slack and accessible for code reviews during work hours.',
    backupUserId: 'usr-12',
    backupUserName: 'Kavita Nair',
    status: 'PENDING_APPROVAL',
    createdAt: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
  },
];

export const INITIAL_CHECKINS: WeeklyCheckin[] = [
  {
    id: 'chk-1',
    userId: 'usr-3',
    userName: 'Rahul Sharma',
    userAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    userJobTitle: 'Senior Fullstack Engineer',
    departmentName: 'Engineering',
    weekNumber: 36,
    year: 2026,
    completedHighlights: 'Finished SCIM 2.0 user deprovisioning webhooks and passed Okta compliance tests.',
    upcomingPriorities: 'Pen-test vulnerability remediations for PKCE and CORS on auth endpoints.',
    activeBlockers: 'None currently on my tasks.',
    supportNeeded: 'Need Aisha from SecOps to re-run the vulnerability scan after Friday deploy.',
    confidence: 'HIGH',
    managerNotes: 'Terrific progress on the SCIM integration Rahul.',
    isReviewed: true,
    submittedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'chk-2',
    userId: 'usr-4',
    userName: 'Priya Patel',
    userAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    userJobTitle: 'Staff Backend Engineer',
    departmentName: 'Engineering',
    weekNumber: 36,
    year: 2026,
    completedHighlights: 'Configured Envoy service mesh retry policies and tuned ClickHouse buffer engine parameters.',
    upcomingPriorities: 'Resolve KMS key access blocker and benchmark consumer lag under 60k req/s load.',
    activeBlockers: 'AWS KMS key IAM delegation pending approval from David Chen.',
    supportNeeded: 'Escalation support on SecOps policy approval to unblock secret replication.',
    confidence: 'MEDIUM',
    managerNotes: 'I will sync with David Chen today to grant the IAM trust relationship.',
    isReviewed: false,
    submittedAt: new Date(Date.now() - 20 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'chk-3',
    userId: 'usr-6',
    userName: 'Ananya Iyer',
    userAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    userJobTitle: 'Senior Product Designer',
    departmentName: 'Product & Design',
    weekNumber: 36,
    year: 2026,
    completedHighlights: 'Built interactive Chart token primitives and delivered Figma variable design tokens for Web.',
    upcomingPriorities: 'Prepare component documentation site and finalize token export for SwiftUI.',
    activeBlockers: 'SwiftUI asset catalog exporter configuration issue.',
    supportNeeded: 'A 30-min sync with mobile developers on asset directory layout.',
    confidence: 'HIGH',
    isReviewed: false,
    submittedAt: new Date(Date.now() - 14 * 60 * 60 * 1000).toISOString(),
  },
];

export const INITIAL_GOALS: Goal[] = [
  {
    id: 'gol-1',
    title: 'Achieve 99.99% Cloud Platform Uptime & Sub-100ms P95 Latency',
    description: 'Company-wide infrastructure reliability and multi-region failover goal for 2026.',
    tier: 'COMPANY',
    status: 'ON_TRACK',
    progress: 84,
    targetDate: '2026-12-31T00:00:00Z',
    ownerId: 'usr-1',
    ownerName: 'Sarah Jenkins',
    ownerAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    departmentName: 'Engineering',
    keyResults: [
      { id: 'kr-1', goalId: 'gol-1', title: 'Global P95 API Latency below 100ms', currentValue: 92, targetValue: 100, metricUnit: 'ms', progress: 92 },
      { id: 'kr-2', goalId: 'gol-1', title: 'Zero unplanned downtime during Q3/Q4 migrations', currentValue: 99.99, targetValue: 99.99, metricUnit: '%', progress: 100 },
      { id: 'kr-3', goalId: 'gol-1', title: 'Full automated cross-region recovery under 60s', currentValue: 45, targetValue: 60, metricUnit: 'sec', progress: 75 },
    ],
  },
  {
    id: 'gol-2',
    title: 'Roll Out Odyssey Design System to 100% of Production Interfaces',
    description: 'Deprecate legacy styling across all web applications and enforce accessible design tokens.',
    tier: 'DEPARTMENT',
    status: 'ON_TRACK',
    progress: 78,
    targetDate: '2026-10-31T00:00:00Z',
    ownerId: 'usr-15',
    ownerName: 'Siddharth Rao',
    ownerAvatar: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=150&auto=format&fit=crop&q=80',
    departmentId: 'dept-2',
    departmentName: 'Product & Design',
    keyResults: [
      { id: 'kr-4', goalId: 'gol-2', title: 'Ship 40+ audited accessible React primitives', currentValue: 34, targetValue: 40, metricUnit: 'components', progress: 85 },
      { id: 'kr-5', goalId: 'gol-2', title: 'WCAG AAA contrast compliance across all screens', currentValue: 96, targetValue: 100, metricUnit: '%', progress: 96 },
      { id: 'kr-6', goalId: 'gol-2', title: '100% automated Figma-to-code token sync', currentValue: 60, targetValue: 100, metricUnit: '%', progress: 60 },
    ],
  },
  {
    id: 'gol-3',
    title: 'Attain SOC2 Type II and ISO 27001 Security Certifications',
    description: 'Complete rigorous compliance audits and implement automated security telemetry.',
    tier: 'DEPARTMENT',
    status: 'ON_TRACK',
    progress: 70,
    targetDate: '2026-11-30T00:00:00Z',
    ownerId: 'usr-11',
    ownerName: 'David Chen',
    ownerAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    departmentId: 'dept-4',
    departmentName: 'Operations & SecOps',
    keyResults: [
      { id: 'kr-7', goalId: 'gol-3', title: '100% employee completion of quarterly security training', currentValue: 94, targetValue: 100, metricUnit: '%', progress: 94 },
      { id: 'kr-8', goalId: 'gol-3', title: 'Automated continuous evidence collection via Vanta', currentValue: 80, targetValue: 100, metricUnit: '%', progress: 80 },
      { id: 'kr-9', goalId: 'gol-3', title: 'Zero critical or high unresolved CVEs in production', currentValue: 0, targetValue: 0, metricUnit: 'CVEs', progress: 100 },
    ],
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'aud-1',
    actorId: 'usr-2',
    actorName: 'Vikram Mehta',
    actorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    actorRole: 'MANAGER',
    action: 'LEAVE_APPROVED',
    entityType: 'LeaveRequest',
    entityId: 'lev-2',
    entityTitle: 'Carlos Mendez - 3 Days Casual Leave',
    previousVal: 'PENDING_APPROVAL',
    newVal: 'APPROVED',
    details: 'Approved with note: All ongoing PRs merged into development branch ahead of time.',
    timestamp: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'aud-2',
    actorId: 'usr-4',
    actorName: 'Priya Patel',
    actorAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    actorRole: 'EMPLOYEE',
    action: 'BLOCKER_REPORTED',
    entityType: 'Blocker',
    entityId: 'blk-1',
    entityTitle: 'AWS KMS Key Access Policy Mismatch',
    previousVal: 'NONE',
    newVal: 'OPEN',
    details: 'Flagged HIGH severity blocker on Cross-Region Secret Replication. Dependency owner: David Chen.',
    timestamp: new Date(Date.now() - 52 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'aud-3',
    actorId: 'usr-3',
    actorName: 'Rahul Sharma',
    actorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    actorRole: 'EMPLOYEE',
    action: 'MISSED_MEETING_EXPLANATION_SUBMITTED',
    entityType: 'MeetingAttendance',
    entityId: 'att-3',
    entityTitle: 'Engineering Daily Standup & Blocker Triage',
    previousVal: 'ABSENT (Unexplained)',
    newVal: 'ABSENT (Explanation: TECHNICAL_ISSUE)',
    details: 'Reason: ISP fiber cut in neighborhood. Back online via backup hotspot.',
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'aud-4',
    actorId: 'usr-1',
    actorName: 'Sarah Jenkins',
    actorAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    actorRole: 'ADMIN',
    action: 'ATTENDANCE_EXCUSED',
    entityType: 'MeetingAttendance',
    entityId: 'att-6',
    entityTitle: 'Daniel Kim - Late Standup Attendance',
    previousVal: 'LATE',
    newVal: 'EXCUSED',
    details: 'Reason accepted: Urgent staging login troubleshooting.',
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    userId: 'usr-1',
    title: 'Missed Meeting Explanation Submitted',
    message: 'Rahul Sharma provided an explanation for missing today’s Engineering Standup (ISP technical issue).',
    type: 'MISSED_MEETING',
    link: '/meetings',
    severity: 'warning',
    isRead: false,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'notif-2',
    userId: 'usr-1',
    title: 'New Leave Request Pending Approval',
    message: 'Ananya Iyer requested 3 days Annual Leave (Sep 14 - Sep 16) with full handover plan.',
    type: 'LEAVE_REQUEST',
    link: '/leave',
    severity: 'info',
    isRead: false,
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'notif-3',
    userId: 'usr-1',
    title: 'Critical Blocker Alert (>48 Hours)',
    message: 'Priya Patel’s task "Cross-Region Secret Replication" has been blocked on AWS KMS IAM permissions for 52 hours.',
    type: 'BLOCKER',
    link: '/blockers',
    severity: 'danger',
    isRead: false,
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'notif-4',
    userId: 'usr-1',
    title: 'Approaching Milestone Deadline',
    message: 'Project Phoenix milestone "Service Mesh & Distributed Tracing" is due in 7 days with 4 tasks in progress.',
    type: 'DEADLINE',
    link: '/work',
    severity: 'warning',
    isRead: true,
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const PROACTIVE_INSIGHTS: InsightCard[] = [
  {
    id: 'ins-1',
    title: 'Task Blocked for More Than 48 Hours',
    description: 'Priya Patel’s critical task "Cross-Region Secret Replication" has been blocked for 52 hours due to pending AWS KMS IAM role delegation owned by David Chen (SecOps).',
    category: 'blockers',
    severity: 'critical',
    evidenceCitations: [
      { label: 'Blocker: AWS KMS Key Policy', entityType: 'Blocker', entityId: 'blk-1' },
      { label: 'Task: Cross-Region Secret Replication', entityType: 'Task', entityId: 'tsk-3' },
      { label: 'Reporter: Priya Patel', entityType: 'User', entityId: 'usr-4' },
      { label: 'Dependency Owner: David Chen', entityType: 'User', entityId: 'usr-11' },
    ],
    suggestedAction: 'Reassign or ping David Chen to approve the cross-account trust policy.',
    actionLabel: 'Triage Blocker',
  },
  {
    id: 'ins-2',
    title: 'Leave Request with High Workload Impact',
    description: 'Ananya Iyer requested 3 days leave (Sep 14 - Sep 16). 1 milestone task is due during her leave window, but handover to Siddharth Rao is 100% complete with 84% team capacity remaining.',
    category: 'leave',
    severity: 'info',
    evidenceCitations: [
      { label: 'Leave: Ananya Iyer (Sep 14-16)', entityType: 'LeaveRequest', entityId: 'lev-1' },
      { label: 'Handover Backup: Siddharth Rao', entityType: 'User', entityId: 'usr-15' },
      { label: 'Project: Odyssey Design System', entityType: 'Project', entityId: 'proj-2' },
    ],
    suggestedAction: 'Review workload intelligence metrics and approve leave with backup coverage.',
    actionLabel: 'Review Workload Intelligence',
  },
  {
    id: 'ins-3',
    title: 'Unexcused Absence Requiring Manager Triage',
    description: 'Rahul Sharma was marked absent for today’s Engineering Standup and submitted a technical explanation (local fiber outage).',
    category: 'workload',
    severity: 'warning',
    evidenceCitations: [
      { label: 'Meeting: Engineering Daily Standup', entityType: 'Meeting', entityId: 'mtg-1' },
      { label: 'Employee: Rahul Sharma', entityType: 'User', entityId: 'usr-3' },
      { label: 'Reason: Technical Issue (Fiber cut)', entityType: 'Attendance', entityId: 'att-3' },
    ],
    suggestedAction: 'Accept explanation, mark attendance as excused, and check connectivity status.',
    actionLabel: 'Review Explanation',
  },
  {
    id: 'ins-4',
    title: 'Project Phoenix Milestone Schedule Tightness',
    description: 'Project Phoenix is at 68% progress with 6 tasks in progress and 2 blocked tasks. Target completion date is in 7 days.',
    category: 'velocity',
    severity: 'warning',
    evidenceCitations: [
      { label: 'Project: Phoenix V2', entityType: 'Project', entityId: 'proj-1' },
      { label: 'Milestone: Service Mesh', entityType: 'Milestone', entityId: 'm-2' },
    ],
    suggestedAction: 'Rebalance subtasks and resolve upstream Kafka/KMS blockers to prevent slip.',
    actionLabel: 'Inspect Project Board',
  },
];
