import {
  User,
  Department,
  Team,
  Project,
  Task,
  Blocker,
  Meeting,
  LeaveRequest,
  WeeklyCheckin,
  Goal,
  AuditLog,
  NotificationItem,
  InsightCard,
  MissedMeetingReason,
  MeetingAttendanceStatus,
} from './types';

// ==========================================
// 1. DEPARTMENTS & TEAMS (VEIXON Structure)
// ==========================================
export const INITIAL_DEPARTMENTS: Department[] = [
  { id: 'dept-1', name: 'Executive Leadership', code: 'EXEC', headName: 'Abhinav Rishi', memberCount: 2 },
  { id: 'dept-2', name: 'Engineering & Technology', code: 'ENG', headName: 'Shlok Karn', memberCount: 4 },
  { id: 'dept-3', name: 'Product & Design Systems', code: 'DESIGN', headName: 'Shabnam Nisha', memberCount: 2 },
  { id: 'dept-4', name: 'Cloud & Infrastructure', code: 'INFRA', headName: 'Suhas', memberCount: 2 },
  { id: 'dept-5', name: 'People & Operations', code: 'PEOPLE', headName: 'Navya', memberCount: 1 },
];

export const INITIAL_TEAMS: Team[] = [
  { id: 'team-1', name: 'Executive Strategy', departmentId: 'dept-1', leadName: 'V S Sai Siddardh', memberCount: 2 },
  { id: 'team-2', name: 'Core Architecture', departmentId: 'dept-2', leadName: 'Shlok Karn', memberCount: 2 },
  { id: 'team-3', name: 'Frontend & UI Engineering', departmentId: 'dept-2', leadName: 'C. Taran Teja', memberCount: 2 },
  { id: 'team-4', name: 'Design Tokens & Ergonomics', departmentId: 'dept-3', leadName: 'Shabnam Nisha', memberCount: 2 },
  { id: 'team-5', name: 'SRE & Kubernetes Cluster', departmentId: 'dept-4', leadName: 'Suhas', memberCount: 2 },
  { id: 'team-6', name: 'QA & Penetration Security', departmentId: 'dept-2', leadName: 'Shivani', memberCount: 1 },
  { id: 'team-7', name: 'People & Culture', departmentId: 'dept-5', leadName: 'Navya', memberCount: 1 },
];

// ==========================================
// 2. OFFICIAL VEIXON TEAM MEMBERS (10 Users)
// ==========================================
export const INITIAL_USERS: User[] = [
  {
    id: 'usr-1',
    name: 'V S Sai Siddardh',
    email: 'siddhardh@veixon.tech',
    avatarUrl: 'https://www.veixon.com/team/siddardha.png',
    jobTitle: 'Co-founder & Director',
    role: 'DIRECTOR',
    departmentId: 'dept-1',
    departmentName: 'Executive Leadership',
    teamId: 'team-1',
    teamName: 'Executive Strategy',
    attendanceStatus: 'WORKING',
    lastActiveAt: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    joinedAt: '2023-01-15T00:00:00Z',
    location: 'Hyderabad, IN',
    timezone: 'IST (UTC+5:30)',
    skills: ['Strategic Architecture', 'Operations', 'Leadership', 'AI Systems', 'Next.js'],
    leaveBalance: { casualTotal: 12, casualUsed: 2, sickTotal: 10, sickUsed: 1, annualTotal: 18, annualUsed: 6 },
  },
  {
    id: 'usr-2',
    name: 'Abhinav Rishi',
    email: 'abhinav@veixon.tech',
    avatarUrl: 'https://www.veixon.com/team/Abhinav.png',
    jobTitle: 'Founder & CEO',
    role: 'ADMIN',
    departmentId: 'dept-1',
    departmentName: 'Executive Leadership',
    teamId: 'team-1',
    teamName: 'Executive Strategy',
    managerId: 'usr-1',
    managerName: 'V S Sai Siddardh',
    attendanceStatus: 'WORKING',
    lastActiveAt: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
    joinedAt: '2023-01-01T00:00:00Z',
    location: 'Hyderabad, IN',
    timezone: 'IST (UTC+5:30)',
    skills: ['Executive Leadership', 'Product Vision', 'Business Scaling', 'Strategic Partnerships'],
    leaveBalance: { casualTotal: 12, casualUsed: 1, sickTotal: 10, sickUsed: 0, annualTotal: 18, annualUsed: 3 },
  },
  {
    id: 'usr-3',
    name: 'Shlok Karn',
    email: 'shlok@veixon.tech',
    avatarUrl: 'https://www.veixon.com/team/shlok.jpeg',
    jobTitle: 'Co-founder & CTO',
    role: 'MANAGER',
    departmentId: 'dept-2',
    departmentName: 'Engineering & Technology',
    teamId: 'team-2',
    teamName: 'Core Architecture',
    managerId: 'usr-1',
    managerName: 'V S Sai Siddardh',
    attendanceStatus: 'WORKING',
    lastActiveAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    joinedAt: '2023-01-15T00:00:00Z',
    location: 'Hyderabad, IN',
    timezone: 'IST (UTC+5:30)',
    skills: ['Distributed Systems', 'Platform Architecture', 'Cloud Infrastructure', 'Go', 'PostgreSQL'],
    leaveBalance: { casualTotal: 12, casualUsed: 3, sickTotal: 10, sickUsed: 0, annualTotal: 18, annualUsed: 4 },
  },
  {
    id: 'usr-4',
    name: 'Suhas',
    email: 'suhas@veixon.tech',
    avatarUrl: 'https://www.veixon.com/team/suhas.png',
    jobTitle: 'Cloud & Infrastructure Lead',
    role: 'MANAGER',
    departmentId: 'dept-4',
    departmentName: 'Cloud & Infrastructure',
    teamId: 'team-5',
    teamName: 'SRE & Kubernetes Cluster',
    managerId: 'usr-3',
    managerName: 'Shlok Karn',
    attendanceStatus: 'LEAVE_ON_DUTY', // Light blue: Duty Leave (informed)
    lastActiveAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    joinedAt: '2023-03-15T00:00:00Z',
    location: 'Hyderabad, IN',
    timezone: 'IST (UTC+5:30)',
    skills: ['AWS', 'Kubernetes', 'Terraform', 'CI/CD', 'Security', 'Prometheus'],
    leaveBalance: { casualTotal: 12, casualUsed: 1, sickTotal: 10, sickUsed: 1, annualTotal: 18, annualUsed: 5 },
  },
  {
    id: 'usr-5',
    name: 'Arjun J',
    email: 'arjun@veixon.tech',
    avatarUrl: 'https://www.veixon.com/team/ARJUN.png',
    jobTitle: 'Software Engineer',
    role: 'EMPLOYEE',
    departmentId: 'dept-2',
    departmentName: 'Engineering & Technology',
    teamId: 'team-2',
    teamName: 'Core Architecture',
    managerId: 'usr-3',
    managerName: 'Shlok Karn',
    attendanceStatus: 'WORKING',
    lastActiveAt: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
    joinedAt: '2023-06-01T00:00:00Z',
    location: 'Hyderabad, IN',
    timezone: 'IST (UTC+5:30)',
    skills: ['Node.js', 'Go', 'Redis', 'PostgreSQL', 'Microservices', 'GraphQL'],
    leaveBalance: { casualTotal: 12, casualUsed: 1, sickTotal: 10, sickUsed: 0, annualTotal: 18, annualUsed: 2 },
  },
  {
    id: 'usr-6',
    name: 'Shabnam Nisha',
    email: 'shabnam@veixon.tech',
    avatarUrl: 'https://www.veixon.com/team/Shabnam.jpeg',
    jobTitle: 'Lead Product Designer',
    role: 'EMPLOYEE',
    departmentId: 'dept-3',
    departmentName: 'Product & Design Systems',
    teamId: 'team-4',
    teamName: 'Design Tokens & Ergonomics',
    managerId: 'usr-1',
    managerName: 'V S Sai Siddardh',
    attendanceStatus: 'DEEP_WORK', // Purple: Focus Mode
    lastActiveAt: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    joinedAt: '2023-05-01T00:00:00Z',
    location: 'Hyderabad, IN',
    timezone: 'IST (UTC+5:30)',
    skills: ['Figma', 'Design Systems', 'UI/UX', 'Design Tokens', 'Micro-interactions'],
    leaveBalance: { casualTotal: 12, casualUsed: 3, sickTotal: 10, sickUsed: 1, annualTotal: 18, annualUsed: 4 },
  },
  {
    id: 'usr-7',
    name: 'C. Taran Teja',
    email: 'taran@veixon.tech',
    avatarUrl: 'https://www.veixon.com/team/taran.jpeg',
    jobTitle: 'Frontend Engineer',
    role: 'EMPLOYEE',
    departmentId: 'dept-2',
    departmentName: 'Engineering & Technology',
    teamId: 'team-3',
    teamName: 'Frontend & UI Engineering',
    managerId: 'usr-1',
    managerName: 'V S Sai Siddardh',
    attendanceStatus: 'WORKING',
    lastActiveAt: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
    joinedAt: '2023-07-01T00:00:00Z',
    location: 'Hyderabad, IN',
    timezone: 'IST (UTC+5:30)',
    skills: ['React', 'Next.js', 'TypeScript', 'Tailwind CSS', 'Framer Motion'],
    leaveBalance: { casualTotal: 12, casualUsed: 2, sickTotal: 10, sickUsed: 0, annualTotal: 18, annualUsed: 6 },
  },
  {
    id: 'usr-8',
    name: 'Navya',
    email: 'navya@veixon.tech',
    avatarUrl: 'https://www.veixon.com/team/NAVYA.jpeg',
    jobTitle: 'Head of People & Operations',
    role: 'HR',
    departmentId: 'dept-5',
    departmentName: 'People & Operations',
    teamId: 'team-7',
    teamName: 'People & Culture',
    managerId: 'usr-2',
    managerName: 'Abhinav Rishi',
    attendanceStatus: 'WORKING',
    lastActiveAt: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
    joinedAt: '2023-04-01T00:00:00Z',
    location: 'Hyderabad, IN',
    timezone: 'IST (UTC+5:30)',
    skills: ['People Operations', 'HR', 'Talent Management', 'Culture', 'Compliance'],
    leaveBalance: { casualTotal: 12, casualUsed: 1, sickTotal: 10, sickUsed: 0, annualTotal: 18, annualUsed: 3 },
  },
  {
    id: 'usr-9',
    name: 'Sreeshith',
    email: 'sreeshith@veixon.tech',
    avatarUrl: 'https://www.veixon.com/team/sreeshith.png',
    jobTitle: 'Lead DevOps / SRE',
    role: 'EMPLOYEE',
    departmentId: 'dept-4',
    departmentName: 'Cloud & Infrastructure',
    teamId: 'team-5',
    teamName: 'SRE & Kubernetes Cluster',
    managerId: 'usr-4',
    managerName: 'Suhas',
    attendanceStatus: 'WORKING',
    lastActiveAt: new Date(Date.now() - 6 * 60 * 1000).toISOString(),
    joinedAt: '2023-08-01T00:00:00Z',
    location: 'Hyderabad, IN',
    timezone: 'IST (UTC+5:30)',
    skills: ['DevOps', 'Kubernetes', 'Prometheus', 'Grafana', 'Terraform', 'CI/CD'],
    leaveBalance: { casualTotal: 12, casualUsed: 5, sickTotal: 10, sickUsed: 1, annualTotal: 18, annualUsed: 9 },
  },
  {
    id: 'usr-10',
    name: 'Shivani',
    email: 'shivani@veixon.tech',
    avatarUrl: 'https://www.veixon.com/team/shivani.jpeg',
    jobTitle: 'QA & Security Engineer',
    role: 'EMPLOYEE',
    departmentId: 'dept-2',
    departmentName: 'Engineering & Technology',
    teamId: 'team-6',
    teamName: 'QA & Penetration Security',
    managerId: 'usr-1',
    managerName: 'V S Sai Siddardh',
    attendanceStatus: 'UNINFORMED_ABSENCE', // Red: Uninformed absence needing explanation
    lastActiveAt: new Date(Date.now() - 120 * 60 * 1000).toISOString(),
    joinedAt: '2023-09-01T00:00:00Z',
    location: 'Hyderabad, IN',
    timezone: 'IST (UTC+5:30)',
    skills: ['QA Automation', 'Playwright', 'Security Testing', 'Jest', 'API Testing'],
    leaveBalance: { casualTotal: 12, casualUsed: 2, sickTotal: 10, sickUsed: 0, annualTotal: 18, annualUsed: 5 },
  },
];

// ==========================================
// 3. OFFICIAL VEIXON PROJECTS (10 Projects)
// ==========================================
export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'proj-1',
    name: 'VEIXON Decisions',
    code: 'DECISIONS',
    description: 'Enterprise decision intelligence platform powered by predictive models and automated analytics.',
    status: 'Active',
    health: 'On Track',
    progress: 74,
    departmentId: 'dept-2',
    teamId: 'team-2',
    leadId: 'usr-1',
    leadName: 'V S Sai Siddardh',
    startDate: '2026-06-01',
    targetDate: '2026-10-31',
    totalTasks: 24,
    completedTasks: 16,
    blockedTasks: 1,
    inProgressTasks: 7,
    milestones: [
      { id: 'm-1', title: 'Decision Graph Engine v1.0', projectId: 'proj-1', dueDate: '2026-08-15', isCompleted: true, progress: 100, taskCount: 8, completedTaskCount: 8 },
      { id: 'm-2', title: 'Stripe Billing & KMS Signing', projectId: 'proj-1', dueDate: '2026-09-20', isCompleted: false, progress: 65, taskCount: 8, completedTaskCount: 4 },
      { id: 'm-3', title: 'Enterprise Multi-tenant Audit', projectId: 'proj-1', dueDate: '2026-10-31', isCompleted: false, progress: 30, taskCount: 8, completedTaskCount: 2 },
    ],
  },
  {
    id: 'proj-2',
    name: 'DayZero Foundary',
    code: 'DAYZERO',
    description: 'Rapid prototyping and incubation engine for next-generation products across industry verticals.',
    status: 'Active',
    health: 'On Track',
    progress: 62,
    departmentId: 'dept-1',
    teamId: 'team-1',
    leadId: 'usr-2',
    leadName: 'Abhinav Rishi',
    startDate: '2026-05-15',
    targetDate: '2026-11-30',
    totalTasks: 18,
    completedTasks: 10,
    blockedTasks: 0,
    inProgressTasks: 8,
    milestones: [
      { id: 'm-4', title: 'Incubation Framework Scaffolding', projectId: 'proj-2', dueDate: '2026-07-30', isCompleted: true, progress: 100, taskCount: 6, completedTaskCount: 6 },
      { id: 'm-5', title: '5 Partner Pilot Workflows', projectId: 'proj-2', dueDate: '2026-10-15', isCompleted: false, progress: 50, taskCount: 6, completedTaskCount: 3 },
      { id: 'm-6', title: 'DayZero Foundry Analytics Portal', projectId: 'proj-2', dueDate: '2026-11-30', isCompleted: false, progress: 20, taskCount: 6, completedTaskCount: 1 },
    ],
  },
  {
    id: 'proj-3',
    name: 'Internal Command Center',
    code: 'COMMAND',
    description: 'Central operational nervous system for company-wide progress tracking, people, and telemetry.',
    status: 'Active',
    health: 'On Track',
    progress: 88,
    departmentId: 'dept-2',
    teamId: 'team-3',
    leadId: 'usr-1',
    leadName: 'V S Sai Siddardh',
    startDate: '2026-04-01',
    targetDate: '2026-09-30',
    totalTasks: 20,
    completedTasks: 17,
    blockedTasks: 0,
    inProgressTasks: 3,
    milestones: [
      { id: 'm-7', title: 'Director Dashboard & Attention Section', projectId: 'proj-3', dueDate: '2026-08-01', isCompleted: true, progress: 100, taskCount: 7, completedTaskCount: 7 },
      { id: 'm-8', title: 'GetLayers Design Remodel & Tokens', projectId: 'proj-3', dueDate: '2026-09-12', isCompleted: true, progress: 100, taskCount: 7, completedTaskCount: 7 },
      { id: 'm-9', title: 'Automated Hardening & QA Audit', projectId: 'proj-3', dueDate: '2026-09-30', isCompleted: false, progress: 80, taskCount: 6, completedTaskCount: 3 },
    ],
  },
  {
    id: 'proj-4',
    name: 'Client Platform Development',
    code: 'CLIENT-CORE',
    description: 'High-throughput enterprise SaaS architecture delivering custom cloud microservices.',
    status: 'Active',
    health: 'At Risk',
    progress: 45,
    departmentId: 'dept-2',
    teamId: 'team-2',
    leadId: 'usr-3',
    leadName: 'Shlok Karn',
    startDate: '2026-06-15',
    targetDate: '2026-10-15',
    totalTasks: 16,
    completedTasks: 6,
    blockedTasks: 2,
    inProgressTasks: 8,
    milestones: [
      { id: 'm-10', title: 'Multi-tenant Isolation Layer', projectId: 'proj-4', dueDate: '2026-08-20', isCompleted: true, progress: 100, taskCount: 5, completedTaskCount: 5 },
      { id: 'm-11', title: 'SSO SAML Handshake & RBAC', projectId: 'proj-4', dueDate: '2026-09-18', isCompleted: false, progress: 40, taskCount: 6, completedTaskCount: 1 },
      { id: 'm-12', title: 'Production Load Testing', projectId: 'proj-4', dueDate: '2026-10-15', isCompleted: false, progress: 15, taskCount: 5, completedTaskCount: 0 },
    ],
  },
  {
    id: 'proj-5',
    name: 'VEIXON Website & Brand',
    code: 'WEB-PORTAL',
    description: 'Official VEIXON web showcase, interactive experience layers, and company portal.',
    status: 'Active',
    health: 'On Track',
    progress: 92,
    departmentId: 'dept-3',
    teamId: 'team-4',
    leadId: 'usr-6',
    leadName: 'Shabnam Nisha',
    startDate: '2026-05-01',
    targetDate: '2026-09-25',
    totalTasks: 12,
    completedTasks: 11,
    blockedTasks: 0,
    inProgressTasks: 1,
    milestones: [
      { id: 'm-13', title: 'Hero Cinematic Layers', projectId: 'proj-5', dueDate: '2026-07-15', isCompleted: true, progress: 100, taskCount: 4, completedTaskCount: 4 },
      { id: 'm-14', title: 'Solutions Showcase Pages', projectId: 'proj-5', dueDate: '2026-08-30', isCompleted: true, progress: 100, taskCount: 4, completedTaskCount: 4 },
      { id: 'm-15', title: 'Final Mobile Optimization', projectId: 'proj-5', dueDate: '2026-09-25', isCompleted: false, progress: 85, taskCount: 4, completedTaskCount: 3 },
    ],
  },
  {
    id: 'proj-6',
    name: 'AI Product Development',
    code: 'AI-ENGINE',
    description: 'Autonomous LLM agent integrations, embedding pipelines, and semantic intelligence workflows.',
    status: 'Active',
    health: 'On Track',
    progress: 58,
    departmentId: 'dept-2',
    teamId: 'team-2',
    leadId: 'usr-1',
    leadName: 'V S Sai Siddardh',
    startDate: '2026-07-01',
    targetDate: '2026-12-15',
    totalTasks: 15,
    completedTasks: 8,
    blockedTasks: 0,
    inProgressTasks: 7,
    milestones: [
      { id: 'm-16', title: 'Vector DB Indexing Pipeline', projectId: 'proj-6', dueDate: '2026-08-30', isCompleted: true, progress: 100, taskCount: 5, completedTaskCount: 5 },
      { id: 'm-17', title: 'Agentic Tool-calling Protocol', projectId: 'proj-6', dueDate: '2026-10-31', isCompleted: false, progress: 50, taskCount: 5, completedTaskCount: 2 },
      { id: 'm-18', title: 'Evaluation Benchmark Suite', projectId: 'proj-6', dueDate: '2026-12-15', isCompleted: false, progress: 20, taskCount: 5, completedTaskCount: 1 },
    ],
  },
  {
    id: 'proj-7',
    name: 'UI/UX Design Systems',
    code: 'DESIGN-SYS',
    description: 'Component architecture, ergonomic tokens, and micro-interactions for modern web platforms.',
    status: 'Active',
    health: 'On Track',
    progress: 81,
    departmentId: 'dept-3',
    teamId: 'team-4',
    leadId: 'usr-6',
    leadName: 'Shabnam Nisha',
    startDate: '2026-04-15',
    targetDate: '2026-10-01',
    totalTasks: 14,
    completedTasks: 11,
    blockedTasks: 0,
    inProgressTasks: 3,
    milestones: [
      { id: 'm-19', title: 'Foundational Dark Mode Palette', projectId: 'proj-7', dueDate: '2026-06-30', isCompleted: true, progress: 100, taskCount: 5, completedTaskCount: 5 },
      { id: 'm-20', title: 'Interactive Form & Modal Kit', projectId: 'proj-7', dueDate: '2026-08-31', isCompleted: true, progress: 100, taskCount: 5, completedTaskCount: 5 },
      { id: 'm-21', title: 'Motion Tokens & Accessible ARIA', projectId: 'proj-7', dueDate: '2026-10-01', isCompleted: false, progress: 60, taskCount: 4, completedTaskCount: 1 },
    ],
  },
  {
    id: 'proj-8',
    name: 'Infrastructure & Performance',
    code: 'INFRA-SRE',
    description: 'Multi-region Kubernetes clusters, zero-downtime CI/CD, and low-latency database sharding.',
    status: 'Active',
    health: 'At Risk',
    progress: 70,
    departmentId: 'dept-4',
    teamId: 'team-5',
    leadId: 'usr-4',
    leadName: 'Suhas',
    startDate: '2026-03-01',
    targetDate: '2026-11-15',
    totalTasks: 16,
    completedTasks: 10,
    blockedTasks: 1,
    inProgressTasks: 5,
    milestones: [
      { id: 'm-22', title: 'EKS Multi-cluster Failover', projectId: 'proj-8', dueDate: '2026-07-15', isCompleted: true, progress: 100, taskCount: 5, completedTaskCount: 5 },
      { id: 'm-23', title: 'Let’s Encrypt Ingress Automation', projectId: 'proj-8', dueDate: '2026-09-15', isCompleted: false, progress: 75, taskCount: 5, completedTaskCount: 3 },
      { id: 'm-24', title: 'Cross-region Database Read Replicas', projectId: 'proj-8', dueDate: '2026-11-15', isCompleted: false, progress: 30, taskCount: 6, completedTaskCount: 2 },
    ],
  },
  {
    id: 'proj-9',
    name: 'System Integration & SecOps',
    code: 'SECOPS',
    description: 'Enterprise IAM policies, audit trails, penetration hardening, and automated compliance.',
    status: 'Active',
    health: 'On Track',
    progress: 64,
    departmentId: 'dept-2',
    teamId: 'team-6',
    leadId: 'usr-10',
    leadName: 'Shivani',
    startDate: '2026-05-01',
    targetDate: '2026-11-30',
    totalTasks: 12,
    completedTasks: 7,
    blockedTasks: 1,
    inProgressTasks: 4,
    milestones: [
      { id: 'm-25', title: 'RBAC Authorization Matrix', projectId: 'proj-9', dueDate: '2026-07-31', isCompleted: true, progress: 100, taskCount: 4, completedTaskCount: 4 },
      { id: 'm-26', title: 'Automated Dependency Vulnerability Scans', projectId: 'proj-9', dueDate: '2026-09-30', isCompleted: false, progress: 60, taskCount: 4, completedTaskCount: 2 },
      { id: 'm-27', title: 'SOC2 Compliance Audit Documentation', projectId: 'proj-9', dueDate: '2026-11-30', isCompleted: false, progress: 25, taskCount: 4, completedTaskCount: 1 },
    ],
  },
  {
    id: 'proj-10',
    name: 'Consulting & Solutions',
    code: 'CONSULTING',
    description: 'Strategic technical consulting, architecture audits, and delivery acceleration for partners.',
    status: 'Active',
    health: 'On Track',
    progress: 50,
    departmentId: 'dept-2',
    teamId: 'team-2',
    leadId: 'usr-3',
    leadName: 'Shlok Karn',
    startDate: '2026-06-01',
    targetDate: '2026-12-31',
    totalTasks: 10,
    completedTasks: 5,
    blockedTasks: 0,
    inProgressTasks: 5,
    milestones: [
      { id: 'm-28', title: 'Architecture Review Playbook', projectId: 'proj-10', dueDate: '2026-08-31', isCompleted: true, progress: 100, taskCount: 3, completedTaskCount: 3 },
      { id: 'm-29', title: 'Performance Audit Diagnostic Tool', projectId: 'proj-10', dueDate: '2026-10-31', isCompleted: false, progress: 40, taskCount: 4, completedTaskCount: 1 },
      { id: 'm-30', title: 'Partner Delivery Acceleration Framework', projectId: 'proj-10', dueDate: '2026-12-31', isCompleted: false, progress: 20, taskCount: 3, completedTaskCount: 1 },
    ],
  },
];

// ==========================================
// 4. GENERATE 110 REALISTIC TASKS
// ==========================================
const RAW_TASK_TITLES = [
  'Finalize authentication middleware & token refresh',
  'Review dashboard information architecture',
  'Implement project health calculation formula',
  'Design mobile calendar and week view agenda',
  'Fix notification duplication on duty leave requests',
  'Review API authorization and server-side RBAC',
  'Prepare VEIXON Decisions dashboard analytics widget',
  'Optimize dashboard query and eliminate N+1 latency',
  'Review landing page animation & prefers-reduced-motion',
  'Complete UI regression testing across mobile viewports',
  'Configure AWS KMS IAM decryption policy for Stripe webhooks',
  'Audit PostgreSQL connection pooling and connection limits',
  'Implement leave balance calculator and rollover logic',
  'Deploy Prometheus alerts for 5xx error spikes',
  'Design elevated card tokens in Tailwind configuration',
  'Implement missed meeting explanation modal and triage',
  'Perform automated accessibility audit and ARIA tag validation',
  'Refactor Kanban drag-and-drop state persistence',
  'Configure GitHub Actions CI workflow for Next.js build',
  'Validate zero-trust header security across all API endpoints',
  'Build Executive Profile Drawer for team directory',
  'Implement What Changed timeline activity calculation',
  'Refactor Attention Required exception filter logic',
  'Setup Redis session storage for high-availability login',
  'Integrate date-fns formatting across calendar agenda',
];

export const INITIAL_TASKS: Task[] = Array.from({ length: 110 }, (_, i) => {
  const templateTitle = RAW_TASK_TITLES[i % RAW_TASK_TITLES.length];
  const user = INITIAL_USERS[i % INITIAL_USERS.length];
  const project = INITIAL_PROJECTS[i % INITIAL_PROJECTS.length];
  const isBlocked = i === 10 || i === 25 || i === 48;
  const isCompleted = !isBlocked && (i % 3 === 0);
  const isInProgress = !isBlocked && !isCompleted && (i % 2 === 0);
  const isReview = !isBlocked && !isCompleted && !isInProgress;

  const status = isBlocked ? 'BLOCKED' : isCompleted ? 'COMPLETED' : isInProgress ? 'IN_PROGRESS' : 'REVIEW';
  const progress = isBlocked ? 35 : isCompleted ? 100 : isInProgress ? 65 : 90;
  const priority = i % 5 === 0 ? 'CRITICAL' : i % 3 === 0 ? 'HIGH' : i % 2 === 0 ? 'MEDIUM' : 'LOW';

  const dueMonth = (i % 3) + 9;
  const dueDay = ((i * 7) % 28) + 1;
  const dueDate = `2026-${dueMonth < 10 ? '0' + dueMonth : dueMonth}-${dueDay < 10 ? '0' + dueDay : dueDay}`;

  return {
    id: `task-${i + 1}`,
    title: `${templateTitle} #${i + 1}`,
    description: `Engineering task assigned under ${project.name}. Ensures architectural correctness, test coverage, and documentation.`,
    projectId: project.id,
    projectName: project.name,
    assigneeId: user.id,
    assigneeName: user.name,
    assigneeAvatar: user.avatarUrl,
    creatorId: 'usr-1',
    status,
    priority,
    progress,
    dueDate,
    estimatedHours: 16,
    loggedHours: isCompleted ? 16 : isBlocked ? 6 : 10,
    subtasks: [
      { id: `st-${i}-1`, title: 'Draft technical design & specification', isCompleted: true },
      { id: `st-${i}-2`, title: 'Implement core functionality & error handling', isCompleted: !isInProgress && !isBlocked },
      { id: `st-${i}-3`, title: 'Write automated unit tests & verify in staging', isCompleted: isCompleted },
    ],
    blockerIds: isBlocked ? [`blk-${(i % 15) + 1}`] : [],
    comments: [
      {
        id: `tc-${i}-1`,
        authorId: 'usr-1',
        authorName: 'V S Sai Siddardh',
        authorAvatar: 'https://www.veixon.com/team/siddardha.png',
        content: `Reviewed sprint milestone alignment for ${project.name}. Progress is on track.`,
        createdAt: new Date(Date.now() - 3600000 * (i + 1)).toISOString(),
      },
    ],
    tags: [project.code, priority, isBlocked ? 'Blocked' : 'Sprint'],
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: new Date(Date.now() - 1800000 * (i % 10)).toISOString(),
  };
});

// ==========================================
// 5. OFFICIAL BLOCKERS (15 Blockers)
// ==========================================
export const INITIAL_BLOCKERS: Blocker[] = [
  {
    id: 'blk-1',
    title: 'AWS KMS Key Policy permissions blocked',
    description: 'Stripe webhook signature decryption failing due to missing IAM KMS decrypt role on staging environment.',
    severity: 'CRITICAL',
    status: 'OPEN',
    taskId: 'task-11',
    taskTitle: 'Configure AWS KMS IAM decryption policy for Stripe webhooks #11',
    projectId: 'proj-1',
    projectName: 'VEIXON Decisions',
    reporterId: 'usr-5',
    reporterName: 'Arjun J',
    reporterAvatar: 'https://www.veixon.com/team/ARJUN.png',
    dependencyOwnerId: 'usr-4',
    dependencyOwnerName: 'Suhas',
    reportedAt: new Date(Date.now() - 42 * 60 * 1000).toISOString(),
    expectedResolution: 'Today, 04:00 PM',
  },
  {
    id: 'blk-2',
    title: 'Enterprise SSO OAuth callback mismatch',
    description: 'Redirect URI mismatch on staging auth cluster during SAML 2.0 handshake with enterprise partner.',
    severity: 'HIGH',
    status: 'IN_PROGRESS',
    taskId: 'task-26',
    taskTitle: 'Review API authorization and server-side RBAC #26',
    projectId: 'proj-4',
    projectName: 'Client Platform Development',
    reporterId: 'usr-7',
    reporterName: 'C. Taran Teja',
    reporterAvatar: 'https://www.veixon.com/team/taran.jpeg',
    dependencyOwnerId: 'usr-3',
    dependencyOwnerName: 'Shlok Karn',
    reportedAt: new Date(Date.now() - 110 * 60 * 1000).toISOString(),
    expectedResolution: 'Tomorrow, 11:00 AM',
  },
  {
    id: 'blk-3',
    title: 'Kubernetes ingress cert-manager rate limited',
    description: 'Let’s Encrypt rate limit encountered on staging subdomains during DNS validation.',
    severity: 'HIGH',
    status: 'ACKNOWLEDGED',
    taskId: 'task-49',
    taskTitle: 'Deploy Prometheus alerts for 5xx error spikes #49',
    projectId: 'proj-8',
    projectName: 'Infrastructure & Performance',
    reporterId: 'usr-9',
    reporterName: 'Sreeshith',
    reporterAvatar: 'https://www.veixon.com/team/sreeshith.png',
    dependencyOwnerId: 'usr-4',
    dependencyOwnerName: 'Suhas',
    reportedAt: new Date(Date.now() - 180 * 60 * 1000).toISOString(),
    expectedResolution: 'Sept 14, 2026',
  },
  {
    id: 'blk-4',
    title: 'PostgreSQL connection pool exhaustion during load test',
    description: 'Prisma Client max connection pool reached under 2500 concurrent synthetic requests.',
    severity: 'HIGH',
    status: 'RESOLVED',
    taskId: 'task-12',
    taskTitle: 'Audit PostgreSQL connection pooling and connection limits #12',
    projectId: 'proj-1',
    projectName: 'VEIXON Decisions',
    reporterId: 'usr-3',
    reporterName: 'Shlok Karn',
    reporterAvatar: 'https://www.veixon.com/team/shlok.jpeg',
    resolverId: 'usr-4',
    resolverName: 'Suhas',
    reportedAt: new Date(Date.now() - 480 * 60 * 1000).toISOString(),
    resolvedAt: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    resolutionNotes: 'Configured PgBouncer transaction pooling with max_client_conn=5000.',
  },
  {
    id: 'blk-5',
    title: 'Figma token export sync mismatch with CSS variables',
    description: 'Surface border token definitions divergent between Design Systems and Tailwind tokens.',
    severity: 'MEDIUM',
    status: 'RESOLVED',
    taskId: 'task-15',
    taskTitle: 'Design elevated card tokens in Tailwind configuration #15',
    projectId: 'proj-7',
    projectName: 'UI/UX Design Systems',
    reporterId: 'usr-6',
    reporterName: 'Shabnam Nisha',
    reporterAvatar: 'https://www.veixon.com/team/Shabnam.jpeg',
    resolverId: 'usr-7',
    resolverName: 'C. Taran Teja',
    reportedAt: new Date(Date.now() - 600 * 60 * 1000).toISOString(),
    resolvedAt: new Date(Date.now() - 120 * 60 * 1000).toISOString(),
    resolutionNotes: 'Standardized on VEIXON Design System tokens in tailwind.config.js.',
  },
  {
    id: 'blk-6',
    title: 'Pending executive sign-off on enterprise client contract',
    description: 'Client Platform deployment waiting on client security review completion.',
    severity: 'MEDIUM',
    status: 'OPEN',
    taskId: 'task-30',
    taskTitle: 'Complete UI regression testing across mobile viewports #30',
    projectId: 'proj-4',
    projectName: 'Client Platform Development',
    reporterId: 'usr-2',
    reporterName: 'Abhinav Rishi',
    reporterAvatar: 'https://www.veixon.com/team/Abhinav.png',
    reportedAt: new Date(Date.now() - 240 * 60 * 1000).toISOString(),
    expectedResolution: 'Sept 15, 2026',
  },
  {
    id: 'blk-7',
    title: 'Redis cluster cache invalidation on user role change',
    description: 'RBAC session permission cache not clearing on immediate role promotion.',
    severity: 'CRITICAL',
    status: 'IN_PROGRESS',
    taskId: 'task-6',
    taskTitle: 'Review API authorization and server-side RBAC #6',
    projectId: 'proj-3',
    projectName: 'Internal Command Center',
    reporterId: 'usr-1',
    reporterName: 'V S Sai Siddardh',
    reporterAvatar: 'https://www.veixon.com/team/siddardha.png',
    dependencyOwnerId: 'usr-3',
    dependencyOwnerName: 'Shlok Karn',
    reportedAt: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
    expectedResolution: 'Today, 06:00 PM',
  },
  {
    id: 'blk-8',
    title: 'Safari mobile backdrop-filter clipping bug',
    description: 'Command Palette backdrop blur causing visual artifact on iOS 17.5 webkit.',
    severity: 'LOW',
    status: 'RESOLVED',
    taskId: 'task-21',
    taskTitle: 'Build Executive Profile Drawer for team directory #21',
    projectId: 'proj-3',
    projectName: 'Internal Command Center',
    reporterId: 'usr-7',
    reporterName: 'C. Taran Teja',
    reporterAvatar: 'https://www.veixon.com/team/taran.jpeg',
    resolverId: 'usr-7',
    resolverName: 'C. Taran Teja',
    reportedAt: new Date(Date.now() - 1440 * 60 * 1000).toISOString(),
    resolvedAt: new Date(Date.now() - 300 * 60 * 1000).toISOString(),
    resolutionNotes: 'Added -webkit-backdrop-filter and hardware transform translateZ(0).',
  },
  {
    id: 'blk-9',
    title: 'Missing QA penetration testing sign-off for v1.2 release',
    description: 'Automated vulnerability scanner identified outdated minor dependency in websocket package.',
    severity: 'HIGH',
    status: 'OPEN',
    taskId: 'task-20',
    taskTitle: 'Validate zero-trust header security across all API endpoints #20',
    projectId: 'proj-9',
    projectName: 'System Integration & SecOps',
    reporterId: 'usr-10',
    reporterName: 'Shivani',
    reporterAvatar: 'https://www.veixon.com/team/shivani.jpeg',
    dependencyOwnerId: 'usr-3',
    dependencyOwnerName: 'Shlok Karn',
    reportedAt: new Date(Date.now() - 320 * 60 * 1000).toISOString(),
    expectedResolution: 'Sept 14, 2026',
  },
  {
    id: 'blk-10',
    title: 'Duty leave coverage gap for DevOps rotation',
    description: 'Secondary on-call engineer required during SRE scheduled field duty.',
    severity: 'MEDIUM',
    status: 'RESOLVED',
    taskId: 'task-14',
    taskTitle: 'Deploy Prometheus alerts for 5xx error spikes #14',
    projectId: 'proj-8',
    projectName: 'Infrastructure & Performance',
    reporterId: 'usr-4',
    reporterName: 'Suhas',
    reporterAvatar: 'https://www.veixon.com/team/suhas.png',
    resolverId: 'usr-9',
    resolverName: 'Sreeshith',
    reportedAt: new Date(Date.now() - 720 * 60 * 1000).toISOString(),
    resolvedAt: new Date(Date.now() - 180 * 60 * 1000).toISOString(),
    resolutionNotes: 'Sreeshith confirmed secondary on-call pager schedule.',
  },
  {
    id: 'blk-11',
    title: 'Elasticsearch index memory pressure on audit log queries',
    description: 'Audit log full text search query taking >450ms on unfiltered time ranges.',
    severity: 'MEDIUM',
    status: 'IN_PROGRESS',
    taskId: 'task-8',
    taskTitle: 'Optimize dashboard query and eliminate N+1 latency #8',
    projectId: 'proj-3',
    projectName: 'Internal Command Center',
    reporterId: 'usr-5',
    reporterName: 'Arjun J',
    reporterAvatar: 'https://www.veixon.com/team/ARJUN.png',
    reportedAt: new Date(Date.now() - 150 * 60 * 1000).toISOString(),
    expectedResolution: 'Tomorrow, 02:00 PM',
  },
  {
    id: 'blk-12',
    title: 'WebRTC screen share renegotiation timeout on Firefox',
    description: 'Meeting module live room dropping frame during high-resolution display shares.',
    severity: 'LOW',
    status: 'OPEN',
    taskId: 'task-4',
    taskTitle: 'Design mobile calendar and week view agenda #4',
    projectId: 'proj-3',
    projectName: 'Internal Command Center',
    reporterId: 'usr-7',
    reporterName: 'C. Taran Teja',
    reporterAvatar: 'https://www.veixon.com/team/taran.jpeg',
    reportedAt: new Date(Date.now() - 400 * 60 * 1000).toISOString(),
    expectedResolution: 'Sept 16, 2026',
  },
  {
    id: 'blk-13',
    title: 'API rate limiting threshold too aggressive for batch exports',
    description: 'CSV reports exporter hitting 429 Too Many Requests after 50 pages.',
    severity: 'MEDIUM',
    status: 'RESOLVED',
    taskId: 'task-19',
    taskTitle: 'Configure GitHub Actions CI workflow for Next.js build #19',
    projectId: 'proj-3',
    projectName: 'Internal Command Center',
    reporterId: 'usr-1',
    reporterName: 'V S Sai Siddardh',
    reporterAvatar: 'https://www.veixon.com/team/siddardha.png',
    resolverId: 'usr-3',
    resolverName: 'Shlok Karn',
    reportedAt: new Date(Date.now() - 1000 * 60 * 1000).toISOString(),
    resolvedAt: new Date(Date.now() - 200 * 60 * 1000).toISOString(),
    resolutionNotes: 'Updated sliding window token bucket limit for internal director accounts.',
  },
  {
    id: 'blk-14',
    title: 'Unresolved database migration lock on staging restart',
    description: 'SQLite dev db locked during parallel test worker launch.',
    severity: 'HIGH',
    status: 'RESOLVED',
    taskId: 'task-18',
    taskTitle: 'Refactor Kanban drag-and-drop state persistence #18',
    projectId: 'proj-3',
    projectName: 'Internal Command Center',
    reporterId: 'usr-9',
    reporterName: 'Sreeshith',
    reporterAvatar: 'https://www.veixon.com/team/sreeshith.png',
    resolverId: 'usr-9',
    resolverName: 'Sreeshith',
    reportedAt: new Date(Date.now() - 1200 * 60 * 1000).toISOString(),
    resolvedAt: new Date(Date.now() - 400 * 60 * 1000).toISOString(),
    resolutionNotes: 'Added SQLite busy_timeout=5000 and WAL journaling mode.',
  },
  {
    id: 'blk-15',
    title: 'Staging environment SSL certificate expiration in 48 hours',
    description: 'Automated certbot renewal script failed due to DNS challenge timeout on Cloudflare.',
    severity: 'HIGH',
    status: 'OPEN',
    taskId: 'task-2',
    taskTitle: 'Review dashboard information architecture #2',
    projectId: 'proj-8',
    projectName: 'Infrastructure & Performance',
    reporterId: 'usr-4',
    reporterName: 'Suhas',
    reporterAvatar: 'https://www.veixon.com/team/suhas.png',
    reportedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    expectedResolution: 'Today, 05:30 PM',
  },
];

// ==========================================
// 6. OFFICIAL MEETINGS (40+ Meetings)
// ==========================================
export const INITIAL_MEETINGS: Meeting[] = Array.from({ length: 42 }, (_, i) => {
  const project = INITIAL_PROJECTS[i % INITIAL_PROJECTS.length];
  const organizer = INITIAL_USERS[i % INITIAL_USERS.length];
  const status = i === 0 ? 'In Progress' : i < 4 ? 'Scheduled' : 'Completed';

  const dateOffset = i < 4 ? 0 : Math.floor(i / 4);
  const scheduledDate = new Date(Date.now() - dateOffset * 86400000);
  const hours = 9 + (i % 8);
  scheduledDate.setHours(hours, (i % 2) * 30, 0, 0);

  const meetingTitles = [
    'Daily Engineering Architecture Standup',
    'Executive Leadership & Strategy Sync',
    'Design Systems & Ergonomics Review',
    'Cloud & Infrastructure SRE Triage',
    'VEIXON Decisions Sprint Planning',
    'DayZero Foundry Incubation Checkpoint',
    'Security Hardening & QA Automation Sync',
    'Client Platform Architecture Alignment',
  ];

  const title = `${meetingTitles[i % meetingTitles.length]} (#${i + 1})`;

  const attendances = INITIAL_USERS.slice(0, 6).map((u, idx) => {
    const isAbsent = idx === 5 && i % 3 === 0;
    const isLate = idx === 4 && i % 4 === 0;
    const isExcused = isAbsent && i % 2 === 0;

    return {
      id: `att-${i}-${u.id}`,
      meetingId: `mtg-${i + 1}`,
      userId: u.id,
      userName: u.name,
      userAvatar: u.avatarUrl,
      userRole: u.role,
      status: (isAbsent ? 'ABSENT' : isLate ? 'LATE' : 'PRESENT') as MeetingAttendanceStatus,
      joinedAt: isAbsent ? undefined : scheduledDate.toISOString(),
      missedReason: isAbsent ? ((isExcused ? 'APPROVED_LEAVE' : 'WORK_CONFLICT') as MissedMeetingReason) : undefined,
      explanationNote: isAbsent ? 'Resolving urgent KMS blocker during sprint window.' : undefined,
      isManagerExcused: isExcused,
      managerFeedback: isExcused ? 'Approved absence due to production duty.' : undefined,
      updatedAt: scheduledDate.toISOString(),
    };
  });

  return {
    id: `mtg-${i + 1}`,
    title,
    description: `Operational coordination for ${project.name}. Focus on blocker resolution, milestone health, and cross-team dependencies.`,
    agenda: '1. Blocker review (10m)\n2. Milestone progress (15m)\n3. Immediate sprint deliverables (15m)\n4. Open floor & questions (5m)',
    meetingUrl: `https://meet.google.com/vex-${(i + 100).toString(36)}-ops`,
    scheduledAt: scheduledDate.toISOString(),
    durationMins: 30,
    organizerId: organizer.id,
    organizerName: organizer.name,
    departmentId: project.departmentId,
    teamId: project.teamId,
    status,
    attendances,
  };
});

// ==========================================
// 7. OFFICIAL LEAVE REQUESTS (20 Requests)
// ==========================================
export const INITIAL_LEAVES: LeaveRequest[] = [
  {
    id: 'lev-1',
    userId: 'usr-7',
    userName: 'C. Taran Teja',
    userAvatar: 'https://www.veixon.com/team/taran.jpeg',
    userJobTitle: 'Frontend Engineer',
    departmentName: 'Engineering & Technology',
    leaveType: 'CASUAL',
    startDate: '2026-09-15',
    endDate: '2026-09-16',
    isHalfDay: false,
    totalDays: 2,
    reason: 'Family celebration and personal commitment.',
    handoverCompleted: true,
    handoverNotes: 'Assigned active task #7 to Shabnam. All PRs merged to staging.',
    backupUserId: 'usr-6',
    backupUserName: 'Shabnam Nisha',
    status: 'APPROVED',
    approverId: 'usr-1',
    approverName: 'V S Sai Siddardh',
    decisionNotes: 'Approved. Handover is complete.',
    decisionAt: '2026-09-11T14:30:00Z',
    createdAt: '2026-09-10T10:00:00Z',
  },
  {
    id: 'lev-2',
    userId: 'usr-5',
    userName: 'Arjun J',
    userAvatar: 'https://www.veixon.com/team/ARJUN.png',
    userJobTitle: 'Software Engineer',
    departmentName: 'Engineering & Technology',
    leaveType: 'WORK_FROM_HOME',
    startDate: '2026-09-18',
    endDate: '2026-09-18',
    isHalfDay: false,
    totalDays: 1,
    reason: 'On-site home network maintenance & remote focus sprint.',
    handoverCompleted: true,
    status: 'APPROVED',
    approverId: 'usr-3',
    approverName: 'Shlok Karn',
    createdAt: '2026-09-11T09:15:00Z',
  },
  {
    id: 'lev-3',
    userId: 'usr-9',
    userName: 'Sreeshith',
    userAvatar: 'https://www.veixon.com/team/sreeshith.png',
    userJobTitle: 'Lead DevOps / SRE',
    departmentName: 'Cloud & Infrastructure',
    leaveType: 'ANNUAL',
    startDate: '2026-09-22',
    endDate: '2026-09-25',
    isHalfDay: false,
    totalDays: 4,
    reason: 'Annual scheduled vacation with family.',
    handoverCompleted: true,
    handoverNotes: 'Suhas taking over primary on-call pager rotation for multi-region EKS cluster.',
    backupUserId: 'usr-4',
    backupUserName: 'Suhas',
    status: 'PENDING_APPROVAL',
    createdAt: '2026-09-12T08:00:00Z',
  },
  {
    id: 'lev-4',
    userId: 'usr-6',
    userName: 'Shabnam Nisha',
    userAvatar: 'https://www.veixon.com/team/Shabnam.jpeg',
    userJobTitle: 'Lead Product Designer',
    departmentName: 'Product & Design Systems',
    leaveType: 'CASUAL',
    startDate: '2026-09-14',
    endDate: '2026-09-14',
    isHalfDay: true,
    halfDaySession: 'Afternoon',
    totalDays: 0.5,
    reason: 'Medical checkup appointment.',
    handoverCompleted: true,
    status: 'APPROVED',
    approverId: 'usr-1',
    approverName: 'V S Sai Siddardh',
    decisionAt: '2026-09-11T16:00:00Z',
    createdAt: '2026-09-11T11:00:00Z',
  },
  {
    id: 'lev-5',
    userId: 'usr-10',
    userName: 'Shivani',
    userAvatar: 'https://www.veixon.com/team/shivani.jpeg',
    userJobTitle: 'QA & Security Engineer',
    departmentName: 'Engineering & Technology',
    leaveType: 'SICK',
    startDate: '2026-09-10',
    endDate: '2026-09-11',
    isHalfDay: false,
    totalDays: 2,
    reason: 'Viral fever recovery.',
    handoverCompleted: false,
    status: 'APPROVED',
    approverId: 'usr-8',
    approverName: 'Navya',
    decisionAt: '2026-09-10T08:30:00Z',
    createdAt: '2026-09-10T08:00:00Z',
  },
  {
    id: 'lev-6',
    userId: 'usr-4',
    userName: 'Suhas',
    userAvatar: 'https://www.veixon.com/team/suhas.png',
    userJobTitle: 'Cloud & Infrastructure Lead',
    departmentName: 'Cloud & Infrastructure',
    leaveType: 'WORK_FROM_HOME',
    startDate: '2026-09-28',
    endDate: '2026-09-29',
    isHalfDay: false,
    totalDays: 2,
    reason: 'DevOps cloud architecture sprint focus.',
    handoverCompleted: true,
    status: 'APPROVED',
    approverId: 'usr-3',
    approverName: 'Shlok Karn',
    createdAt: '2026-09-11T13:00:00Z',
  },
  {
    id: 'lev-7',
    userId: 'usr-5',
    userName: 'Arjun J',
    userAvatar: 'https://www.veixon.com/team/ARJUN.png',
    userJobTitle: 'Software Engineer',
    departmentName: 'Engineering & Technology',
    leaveType: 'CASUAL',
    startDate: '2026-10-02',
    endDate: '2026-10-02',
    isHalfDay: false,
    totalDays: 1,
    reason: 'Festival holiday with family.',
    handoverCompleted: true,
    backupUserId: 'usr-3',
    backupUserName: 'Shlok Karn',
    status: 'PENDING_APPROVAL',
    createdAt: '2026-09-12T09:30:00Z',
  },
  {
    id: 'lev-8',
    userId: 'usr-7',
    userName: 'C. Taran Teja',
    userAvatar: 'https://www.veixon.com/team/taran.jpeg',
    userJobTitle: 'Frontend Engineer',
    departmentName: 'Engineering & Technology',
    leaveType: 'ANNUAL',
    startDate: '2026-10-10',
    endDate: '2026-10-15',
    isHalfDay: false,
    totalDays: 5,
    reason: 'Travel and personal wellness.',
    handoverCompleted: true,
    handoverNotes: 'Component library tasks assigned to Shabnam.',
    backupUserId: 'usr-6',
    backupUserName: 'Shabnam Nisha',
    status: 'PENDING_APPROVAL',
    createdAt: '2026-09-12T10:00:00Z',
  },
  {
    id: 'lev-9',
    userId: 'usr-8',
    userName: 'Navya',
    userAvatar: 'https://www.veixon.com/team/NAVYA.jpeg',
    userJobTitle: 'Head of People & Operations',
    departmentName: 'People & Operations',
    leaveType: 'CASUAL',
    startDate: '2026-09-16',
    endDate: '2026-09-16',
    isHalfDay: false,
    totalDays: 1,
    reason: 'HR Leadership summit in Hyderabad.',
    handoverCompleted: true,
    status: 'APPROVED',
    approverId: 'usr-2',
    approverName: 'Abhinav Rishi',
    decisionAt: '2026-09-11T17:00:00Z',
    createdAt: '2026-09-11T12:00:00Z',
  },
  {
    id: 'lev-10',
    userId: 'usr-3',
    userName: 'Shlok Karn',
    userAvatar: 'https://www.veixon.com/team/shlok.jpeg',
    userJobTitle: 'Co-founder & CTO',
    departmentName: 'Engineering & Technology',
    leaveType: 'WORK_FROM_HOME',
    startDate: '2026-09-17',
    endDate: '2026-09-17',
    isHalfDay: false,
    totalDays: 1,
    reason: 'System architecture deep work session.',
    handoverCompleted: true,
    status: 'APPROVED',
    approverId: 'usr-1',
    approverName: 'V S Sai Siddardh',
    decisionAt: '2026-09-11T18:00:00Z',
    createdAt: '2026-09-11T15:00:00Z',
  },
  // Additional 10 historical records for statistics
  ...Array.from({ length: 10 }, (_, i) => ({
    id: `lev-hist-${i + 11}`,
    userId: INITIAL_USERS[i % INITIAL_USERS.length].id,
    userName: INITIAL_USERS[i % INITIAL_USERS.length].name,
    userAvatar: INITIAL_USERS[i % INITIAL_USERS.length].avatarUrl,
    userJobTitle: INITIAL_USERS[i % INITIAL_USERS.length].jobTitle,
    departmentName: INITIAL_USERS[i % INITIAL_USERS.length].departmentName,
    leaveType: (i % 2 === 0 ? 'CASUAL' : 'SICK') as any,
    startDate: `2026-08-${10 + i}`,
    endDate: `2026-08-${11 + i}`,
    isHalfDay: false,
    totalDays: 2,
    reason: 'Historical completed leave log.',
    handoverCompleted: true,
    status: 'APPROVED' as any,
    approverId: 'usr-1',
    approverName: 'V S Sai Siddardh',
    decisionAt: `2026-08-${9 + i}T12:00:00Z`,
    createdAt: `2026-08-${8 + i}T10:00:00Z`,
  })),
];

// ==========================================
// 8. OFFICIAL GOALS / OKRs (10 Goals)
// ==========================================
export const INITIAL_GOALS: Goal[] = [
  {
    id: 'goal-1',
    title: 'Launch VEIXON Decisions Platform v1.0',
    description: 'Full commercial release with enterprise decision graph, predictive analytics, and automated reporting.',
    tier: 'COMPANY',
    status: 'ON_TRACK',
    progress: 85,
    targetDate: '2026-10-31',
    ownerId: 'usr-1',
    ownerName: 'V S Sai Siddardh',
    ownerAvatar: 'https://www.veixon.com/team/siddardha.png',
    departmentId: 'dept-2',
    departmentName: 'Engineering & Technology',
    keyResults: [
      { id: 'kr-1-1', title: 'Achieve <80ms P99 decision evaluation latency', currentValue: 72, targetValue: 80, metricUnit: 'ms', progress: 90 },
      { id: 'kr-1-2', title: 'Complete Stripe webhook encryption with KMS', currentValue: 85, targetValue: 100, metricUnit: '%', progress: 85 },
      { id: 'kr-1-3', title: 'Onboard 3 enterprise launch pilot customers', currentValue: 2, targetValue: 3, metricUnit: 'clients', progress: 67 },
    ],
  },
  {
    id: 'goal-2',
    title: 'Scale DayZero Foundary to 5 Active Incubation Pilots',
    description: 'Deliver 5 enterprise incubation workflows with high satisfaction and rapid prototype turnaround.',
    tier: 'COMPANY',
    status: 'ON_TRACK',
    progress: 60,
    targetDate: '2026-11-30',
    ownerId: 'usr-2',
    ownerName: 'Abhinav Rishi',
    ownerAvatar: 'https://www.veixon.com/team/Abhinav.png',
    departmentId: 'dept-1',
    departmentName: 'Executive Leadership',
    keyResults: [
      { id: 'kr-2-1', title: 'Execute 5 customer discovery sprints', currentValue: 3, targetValue: 5, metricUnit: 'sprints', progress: 60 },
      { id: 'kr-2-2', title: 'Maintain >90% founder Net Promoter Score', currentValue: 94, targetValue: 90, metricUnit: 'NPS', progress: 100 },
    ],
  },
  {
    id: 'goal-3',
    title: 'Achieve 99.99% Core Service Uptime across Multi-Region AWS',
    description: 'Zero unplanned downtime on production microservices and automated failover.',
    tier: 'DEPARTMENT',
    status: 'ON_TRACK',
    progress: 92,
    targetDate: '2026-12-31',
    ownerId: 'usr-4',
    ownerName: 'Suhas',
    ownerAvatar: 'https://www.veixon.com/team/suhas.png',
    departmentId: 'dept-4',
    departmentName: 'Cloud & Infrastructure',
    keyResults: [
      { id: 'kr-3-1', title: 'Maintain 99.99% SLA across ap-south-1 and us-east-1', currentValue: 99.99, targetValue: 99.99, metricUnit: '%', progress: 100 },
      { id: 'kr-3-2', title: 'Automate zero-downtime blue/green deployments', currentValue: 100, targetValue: 100, metricUnit: '%', progress: 100 },
    ],
  },
  {
    id: 'goal-4',
    title: 'Deliver Universal VEIXON Design Tokens across Web & Mobile',
    description: 'Single unified design system used across 100% of internal frontends and web products.',
    tier: 'DEPARTMENT',
    status: 'ON_TRACK',
    progress: 78,
    targetDate: '2026-09-30',
    ownerId: 'usr-6',
    ownerName: 'Shabnam Nisha',
    ownerAvatar: 'https://www.veixon.com/team/Shabnam.jpeg',
    departmentId: 'dept-3',
    departmentName: 'Product & Design Systems',
    keyResults: [
      { id: 'kr-4-1', title: 'Migrate 100% of Command Center UI to design tokens', currentValue: 95, targetValue: 100, metricUnit: '%', progress: 95 },
      { id: 'kr-4-2', title: 'Publish Figma Token Sync v2 library', currentValue: 100, targetValue: 100, metricUnit: '%', progress: 100 },
    ],
  },
  {
    id: 'goal-5',
    title: 'Zero High-Severity Vulnerabilities in Production Deployments',
    description: 'Enforce strict SAST, DAST, and container security scans on all PRs.',
    tier: 'DEPARTMENT',
    status: 'ON_TRACK',
    progress: 70,
    targetDate: '2026-10-15',
    ownerId: 'usr-10',
    ownerName: 'Shivani',
    ownerAvatar: 'https://www.veixon.com/team/shivani.jpeg',
    departmentId: 'dept-2',
    departmentName: 'Engineering & Technology',
    keyResults: [
      { id: 'kr-5-1', title: '100% automated CI penetration scan coverage', currentValue: 100, targetValue: 100, metricUnit: '%', progress: 100 },
      { id: 'kr-5-2', title: 'Resolve all open Snyk and npm audit warnings', currentValue: 88, targetValue: 100, metricUnit: '%', progress: 88 },
    ],
  },
];

// ==========================================
// 9. OFFICIAL AUDIT LOGS (200+ Events)
// ==========================================
export const INITIAL_AUDIT_LOGS: AuditLog[] = Array.from({ length: 205 }, (_, i) => {
  const actor = INITIAL_USERS[i % INITIAL_USERS.length];
  const actions = [
    'TASK_STATUS_UPDATED',
    'BLOCKER_REPORTED',
    'LEAVE_REQUEST_SUBMITTED',
    'MEETING_ATTENDANCE_LOGGED',
    'SECURITY_POLICY_CHECKED',
    'PROJECT_MILESTONE_COMPLETED',
    'ROLE_PERMISSION_VERIFIED',
    'CHECKIN_SAVED',
  ];
  const action = actions[i % actions.length];

  return {
    id: `audit-${i + 1}`,
    actorId: actor.id,
    actorName: actor.name,
    actorAvatar: actor.avatarUrl,
    actorRole: actor.role,
    action,
    entityType: i % 2 === 0 ? 'Task' : 'Project',
    entityId: `REF-${2000 + i}`,
    entityTitle: `Operation Ref WP-AUDIT-${100 + i}`,
    details: `Action [${action}] executed by ${actor.name} (${actor.jobTitle}) on entity REF-${2000 + i}.`,
    timestamp: new Date(Date.now() - (i + 1) * 3600000).toISOString(),
  };
});

// ==========================================
// 10. OFFICIAL NOTIFICATIONS (50 Items)
// ==========================================
export const INITIAL_NOTIFICATIONS: NotificationItem[] = Array.from({ length: 50 }, (_, i) => {
  const notifTypes: NotificationItem['type'][] = [
    'BLOCKER',
    'LEAVE_REQUEST',
    'MISSED_MEETING',
    'DEADLINE',
    'APPROVAL',
    'CHECKIN',
  ];
  const type = notifTypes[i % notifTypes.length];
  const user = INITIAL_USERS[i % INITIAL_USERS.length];

  const titles = {
    BLOCKER: 'Critical Blocker Reported',
    LEAVE_REQUEST: 'New Leave Request Awaiting Sign-off',
    MISSED_MEETING: 'Missed Meeting Requires Explanation',
    DEADLINE: 'Project Milestone Due in 48 Hours',
    APPROVAL: 'Leave Request Approved by Director',
    CHECKIN: 'Weekly Status Check-in Received',
  };

  const messages = {
    BLOCKER: `${user.name} reported a high-priority blocker on Project ${INITIAL_PROJECTS[i % INITIAL_PROJECTS.length].name}.`,
    LEAVE_REQUEST: `${user.name} submitted a leave request for review.`,
    MISSED_MEETING: `${user.name} was marked absent for standup and provided explanation.`,
    DEADLINE: `${INITIAL_PROJECTS[i % INITIAL_PROJECTS.length].name} milestone deadline is approaching.`,
    APPROVAL: `Your leave request was reviewed and approved.`,
    CHECKIN: `${user.name} submitted their 1-minute daily progress update.`,
  };

  return {
    id: `notif-${i + 1}`,
    userId: 'usr-1',
    title: titles[type],
    message: messages[type],
    type,
    severity: (type === 'BLOCKER' ? 'danger' : type === 'DEADLINE' ? 'warning' : 'info') as any,
    isRead: i > 3,
    createdAt: new Date(Date.now() - (i + 1) * 1800000).toISOString(),
  };
});

// ==========================================
// 11. WEEKLY CHECKINS
// ==========================================
export const INITIAL_CHECKINS: WeeklyCheckin[] = INITIAL_USERS.map((u, i) => ({
  id: `chk-${i + 1}`,
  userId: u.id,
  userName: u.name,
  userAvatar: u.avatarUrl,
  userJobTitle: u.jobTitle,
  departmentName: u.departmentName,
  weekNumber: 37,
  year: 2026,
  completedHighlights: 'Completed core refactoring, merged staging branches, and resolved API performance bottlenecks.',
  upcomingPriorities: 'Sprint delivery, automated regression suites, and cross-browser accessibility audit.',
  activeBlockers: i === 4 ? 'Waiting on AWS KMS IAM decryption policy.' : 'None',
  supportNeeded: 'None, fully aligned.',
  confidence: i === 4 ? 'MEDIUM' : 'HIGH',
  isReviewed: i !== 4,
  submittedAt: new Date(Date.now() - (i + 1) * 7200000).toISOString(),
}));

// ==========================================
// 12. PROACTIVE AI INSIGHTS
// ==========================================
export const PROACTIVE_INSIGHTS: InsightCard[] = [
  {
    id: 'ins-1',
    title: 'Stripe KMS Blocker Impacting Staging Release',
    description: 'Arjun J reported an AWS KMS IAM policy blocker on VEIXON Decisions. Resolving this unblocks 3 related tasks.',
    category: 'blockers',
    severity: 'critical',
    evidenceCitations: [
      { label: 'Blocker #1', entityType: 'Blocker', entityId: 'blk-1' },
      { label: 'Task #11', entityType: 'Task', entityId: 'task-11' },
    ],
    suggestedAction: 'Assign IAM policy update to Suhas (DevOps Lead)',
    actionLabel: 'Assign & Unblock',
  },
  {
    id: 'ins-2',
    title: 'Sprint Velocity Up +14% Across Engineering',
    description: '17 tasks completed across the last 48 hours following the unified design token rollout.',
    category: 'velocity',
    severity: 'positive',
    evidenceCitations: [{ label: '17 Completed Tasks', entityType: 'Task', entityId: 'task-1' }],
    suggestedAction: 'View Sprint Velocity Report',
    actionLabel: 'Open Reports',
  },
];
