import {
  User,
  Department,
  Team,
  Project,
  Task,
  Blocker,
  Meeting,
  LeaveRequest,
  WeeklyCheckin,
  Goal,
  AuditLog,
  NotificationItem,
  InsightCard,
  MissedMeetingReason,
  MeetingAttendanceStatus,
} from './types';

// ==========================================
// 1. DEPARTMENTS & TEAMS (VEIXON Structure)
// ==========================================
export const INITIAL_DEPARTMENTS: Department[] = [
  { id: 'dept-1', name: 'Executive Leadership', code: 'EXEC', headName: 'Abhinav Rishi', memberCount: 2 },
  { id: 'dept-2', name: 'Engineering & Technology', code: 'ENG', headName: 'Shlok Karn', memberCount: 4 },
  { id: 'dept-3', name: 'Product & Design Systems', code: 'DESIGN', headName: 'Shabnam Nisha', memberCount: 2 },
  { id: 'dept-4', name: 'Cloud & Infrastructure', code: 'INFRA', headName: 'Suhas', memberCount: 2 },
  { id: 'dept-5', name: 'People & Operations', code: 'PEOPLE', headName: 'Navya', memberCount: 1 },
];

export const INITIAL_TEAMS: Team[] = [
  { id: 'team-1', name: 'Executive Strategy', departmentId: 'dept-1', leadName: 'V S Sai Siddardh', memberCount: 2 },
  { id: 'team-2', name: 'Core Architecture', departmentId: 'dept-2', leadName: 'Shlok Karn', memberCount: 2 },
  { id: 'team-3', name: 'Frontend & UI Engineering', departmentId: 'dept-2', leadName: 'C. Taran Teja', memberCount: 2 },
  { id: 'team-4', name: 'Design Tokens & Ergonomics', departmentId: 'dept-3', leadName: 'Shabnam Nisha', memberCount: 2 },
  { id: 'team-5', name: 'SRE & Kubernetes Cluster', departmentId: 'dept-4', leadName: 'Suhas', memberCount: 2 },
  { id: 'team-6', name: 'QA & Penetration Security', departmentId: 'dept-2', leadName: 'Shivani', memberCount: 1 },
  { id: 'team-7', name: 'People & Culture', departmentId: 'dept-5', leadName: 'Navya', memberCount: 1 },
];

// ==========================================
// 2. OFFICIAL VEIXON TEAM MEMBERS (10 Users)
// ==========================================
export const INITIAL_USERS: User[] = [
  {
    id: 'usr-1',
    name: 'V S Sai Siddardh',
    email: 'siddhardh@veixon.tech',
    avatarUrl: 'https://www.veixon.com/team/siddardha.png',
    jobTitle: 'Co-founder & Director',
    role: 'DIRECTOR',
    departmentId: 'dept-1',
    departmentName: 'Executive Leadership',
    teamId: 'team-1',
    teamName: 'Executive Strategy',
    attendanceStatus: 'WORKING',
    lastActiveAt: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    joinedAt: '2023-01-15T00:00:00Z',
    location: 'Hyderabad, IN',
    timezone: 'IST (UTC+5:30)',
    skills: ['Strategic Architecture', 'Operations', 'Leadership', 'AI Systems', 'Next.js'],
    leaveBalance: { casualTotal: 12, casualUsed: 2, sickTotal: 10, sickUsed: 1, annualTotal: 18, annualUsed: 6 },
  },
  {
    id: 'usr-2',
    name: 'Abhinav Rishi',
    email: 'abhinav@veixon.tech',
    avatarUrl: 'https://www.veixon.com/team/Abhinav.png',
    jobTitle: 'Founder & CEO',
    role: 'ADMIN',
    departmentId: 'dept-1',
    departmentName: 'Executive Leadership',
    teamId: 'team-1',
    teamName: 'Executive Strategy',
    managerId: 'usr-1',
    managerName: 'V S Sai Siddardh',
    attendanceStatus: 'WORKING',
    lastActiveAt: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
    joinedAt: '2023-01-01T00:00:00Z',
    location: 'Hyderabad, IN',
    timezone: 'IST (UTC+5:30)',
    skills: ['Executive Leadership', 'Product Vision', 'Business Scaling', 'Strategic Partnerships'],
    leaveBalance: { casualTotal: 12, casualUsed: 1, sickTotal: 10, sickUsed: 0, annualTotal: 18, annualUsed: 3 },
  },
  {
    id: 'usr-3',
    name: 'Shlok Karn',
    email: 'shlok@veixon.tech',
    avatarUrl: 'https://www.veixon.com/team/shlok.jpeg',
    jobTitle: 'Co-founder & CTO',
    role: 'MANAGER',
    departmentId: 'dept-2',
    departmentName: 'Engineering & Technology',
    teamId: 'team-2',
    teamName: 'Core Architecture',
    managerId: 'usr-1',
    managerName: 'V S Sai Siddardh',
    attendanceStatus: 'WORKING',
    lastActiveAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    joinedAt: '2023-01-15T00:00:00Z',
    location: 'Hyderabad, IN',
    timezone: 'IST (UTC+5:30)',
    skills: ['Distributed Systems', 'Platform Architecture', 'Cloud Infrastructure', 'Go', 'PostgreSQL'],
    leaveBalance: { casualTotal: 12, casualUsed: 3, sickTotal: 10, sickUsed: 0, annualTotal: 18, annualUsed: 4 },
  },
  {
    id: 'usr-4',
    name: 'Suhas',
    email: 'suhas@veixon.tech',
    avatarUrl: 'https://www.veixon.com/team/suhas.png',
    jobTitle: 'Cloud & Infrastructure Lead',
    role: 'MANAGER',
    departmentId: 'dept-4',
    departmentName: 'Cloud & Infrastructure',
    teamId: 'team-5',
    teamName: 'SRE & Kubernetes Cluster',
    managerId: 'usr-3',
    managerName: 'Shlok Karn',
    attendanceStatus: 'LEAVE_ON_DUTY',
    lastActiveAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    joinedAt: '2023-03-15T00:00:00Z',
    location: 'Hyderabad, IN',
    timezone: 'IST (UTC+5:30)',
    skills: ['AWS', 'Kubernetes', 'Terraform', 'CI/CD', 'Security', 'Prometheus'],
    leaveBalance: { casualTotal: 12, casualUsed: 1, sickTotal: 10, sickUsed: 1, annualTotal: 18, annualUsed: 5 },
  },
  {
    id: 'usr-5',
    name: 'Arjun J',
    email: 'arjun@veixon.tech',
    avatarUrl: 'https://www.veixon.com/team/ARJUN.png',
    jobTitle: 'Software Engineer',
    role: 'EMPLOYEE',
    departmentId: 'dept-2',
    departmentName: 'Engineering & Technology',
    teamId: 'team-2',
    teamName: 'Core Architecture',
    managerId: 'usr-3',
    managerName: 'Shlok Karn',
    attendanceStatus: 'WORKING',
    lastActiveAt: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
    joinedAt: '2023-06-01T00:00:00Z',
    location: 'Hyderabad, IN',
    timezone: 'IST (UTC+5:30)',
    skills: ['Node.js', 'Go', 'Redis', 'PostgreSQL', 'Microservices', 'GraphQL'],
    leaveBalance: { casualTotal: 12, casualUsed: 1, sickTotal: 10, sickUsed: 0, annualTotal: 18, annualUsed: 2 },
  },
  {
    id: 'usr-6',
    name: 'Shabnam Nisha',
    email: 'shabnam@veixon.tech',
    avatarUrl: 'https://www.veixon.com/team/Shabnam.jpeg',
    jobTitle: 'Lead Product Designer',
    role: 'EMPLOYEE',
    departmentId: 'dept-3',
    departmentName: 'Product & Design Systems',
    teamId: 'team-4',
    teamName: 'Design Tokens & Ergonomics',
    managerId: 'usr-1',
    managerName: 'V S Sai Siddardh',
    attendanceStatus: 'DEEP_WORK',
    lastActiveAt: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    joinedAt: '2023-05-01T00:00:00Z',
    location: 'Hyderabad, IN',
    timezone: 'IST (UTC+5:30)',
    skills: ['Figma', 'Design Systems', 'UI/UX', 'Design Tokens', 'Micro-interactions'],
    leaveBalance: { casualTotal: 12, casualUsed: 3, sickTotal: 10, sickUsed: 1, annualTotal: 18, annualUsed: 4 },
  },
  {
    id: 'usr-7',
    name: 'C. Taran Teja',
    email: 'taran@veixon.tech',
    avatarUrl: 'https://www.veixon.com/team/taran.jpeg',
    jobTitle: 'Frontend Engineer',
    role: 'EMPLOYEE',
    departmentId: 'dept-2',
    departmentName: 'Engineering & Technology',
    teamId: 'team-3',
    teamName: 'Frontend & UI Engineering',
    managerId: 'usr-1',
    managerName: 'V S Sai Siddardh',
    attendanceStatus: 'WORKING',
    lastActiveAt: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
    joinedAt: '2023-07-01T00:00:00Z',
    location: 'Hyderabad, IN',
    timezone: 'IST (UTC+5:30)',
    skills: ['React', 'Next.js', 'TypeScript', 'Tailwind CSS', 'Framer Motion'],
    leaveBalance: { casualTotal: 12, casualUsed: 2, sickTotal: 10, sickUsed: 0, annualTotal: 18, annualUsed: 6 },
  },
  {
    id: 'usr-8',
    name: 'Navya',
    email: 'navya@veixon.tech',
    avatarUrl: 'https://www.veixon.com/team/NAVYA.jpeg',
    jobTitle: 'Head of People & Operations',
    role: 'HR',
    departmentId: 'dept-5',
    departmentName: 'People & Operations',
    teamId: 'team-7',
    teamName: 'People & Culture',
    managerId: 'usr-2',
    managerName: 'Abhinav Rishi',
    attendanceStatus: 'WORKING',
    lastActiveAt: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
    joinedAt: '2023-04-01T00:00:00Z',
    location: 'Hyderabad, IN',
    timezone: 'IST (UTC+5:30)',
    skills: ['People Operations', 'HR', 'Talent Management', 'Culture', 'Compliance'],
    leaveBalance: { casualTotal: 12, casualUsed: 1, sickTotal: 10, sickUsed: 0, annualTotal: 18, annualUsed: 3 },
  },
  {
    id: 'usr-9',
    name: 'Sreeshith',
    email: 'sreeshith@veixon.tech',
    avatarUrl: 'https://www.veixon.com/team/sreeshith.png',
    jobTitle: 'Lead DevOps / SRE',
    role: 'EMPLOYEE',
    departmentId: 'dept-4',
    departmentName: 'Cloud & Infrastructure',
    teamId: 'team-5',
    teamName: 'SRE & Kubernetes Cluster',
    managerId: 'usr-4',
    managerName: 'Suhas',
    attendanceStatus: 'WORKING',
    lastActiveAt: new Date(Date.now() - 6 * 60 * 1000).toISOString(),
    joinedAt: '2023-08-01T00:00:00Z',
    location: 'Hyderabad, IN',
    timezone: 'IST (UTC+5:30)',
    skills: ['DevOps', 'Kubernetes', 'Prometheus', 'Grafana', 'Terraform', 'CI/CD'],
    leaveBalance: { casualTotal: 12, casualUsed: 5, sickTotal: 10, sickUsed: 1, annualTotal: 18, annualUsed: 9 },
  },
  {
    id: 'usr-10',
    name: 'Shivani',
    email: 'shivani@veixon.tech',
    avatarUrl: 'https://www.veixon.com/team/shivani.jpeg',
    jobTitle: 'QA & Security Engineer',
    role: 'EMPLOYEE',
    departmentId: 'dept-2',
    departmentName: 'Engineering & Technology',
    teamId: 'team-6',
    teamName: 'QA & Penetration Security',
    managerId: 'usr-1',
    managerName: 'V S Sai Siddardh',
    attendanceStatus: 'UNINFORMED_ABSENCE',
    lastActiveAt: new Date(Date.now() - 120 * 60 * 1000).toISOString(),
    joinedAt: '2023-09-01T00:00:00Z',
    location: 'Hyderabad, IN',
    timezone: 'IST (UTC+5:30)',
    skills: ['QA Automation', 'Playwright', 'Security Testing', 'Jest', 'API Testing'],
    leaveBalance: { casualTotal: 12, casualUsed: 2, sickTotal: 10, sickUsed: 0, annualTotal: 18, annualUsed: 5 },
  },
];

// ==========================================
// 3. OFFICIAL VEIXON PROJECTS (5 Core Flagships)
// ==========================================
export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'proj-1',
    name: 'VEIXON Decisions',
    code: 'DECISIONS',
    description: 'Enterprise decision intelligence platform powered by predictive models and automated analytics.',
    status: 'Active',
    health: 'On Track',
    progress: 74,
    departmentId: 'dept-2',
    teamId: 'team-2',
    leadId: 'usr-1',
    leadName: 'V S Sai Siddardh',
    startDate: '2026-06-01',
    targetDate: '2026-10-31',
    totalTasks: 3,
    completedTasks: 1,
    blockedTasks: 1,
    inProgressTasks: 1,
    milestones: [
      { id: 'm-1', title: 'Decision Graph Engine v1.0', projectId: 'proj-1', dueDate: '2026-08-15', isCompleted: true, progress: 100, taskCount: 2, completedTaskCount: 2 },
      { id: 'm-2', title: 'Stripe Billing & KMS Signing', projectId: 'proj-1', dueDate: '2026-09-20', isCompleted: false, progress: 50, taskCount: 2, completedTaskCount: 1 },
    ],
  },
  {
    id: 'proj-2',
    name: 'DayZero Foundary',
    code: 'DAYZERO',
    description: 'Rapid prototyping and incubation engine for next-generation products across industry verticals.',
    status: 'Active',
    health: 'On Track',
    progress: 60,
    departmentId: 'dept-1',
    teamId: 'team-1',
    leadId: 'usr-2',
    leadName: 'Abhinav Rishi',
    startDate: '2026-05-15',
    targetDate: '2026-11-30',
    totalTasks: 2,
    completedTasks: 1,
    blockedTasks: 0,
    inProgressTasks: 1,
    milestones: [
      { id: 'm-3', title: 'Incubation Framework Alpha', projectId: 'proj-2', dueDate: '2026-09-15', isCompleted: false, progress: 60, taskCount: 2, completedTaskCount: 1 },
    ],
  },
  {
    id: 'proj-3',
    name: 'VEIXON Core Infrastructure',
    code: 'INFRA-CORE',
    description: 'Zero-trust multi-region Kubernetes cluster, edge caching mesh, and automated CI/CD pipeline.',
    status: 'Active',
    health: 'On Track',
    progress: 82,
    departmentId: 'dept-4',
    teamId: 'team-5',
    leadId: 'usr-4',
    leadName: 'Suhas',
    startDate: '2026-01-10',
    targetDate: '2026-12-31',
    totalTasks: 2,
    completedTasks: 1,
    blockedTasks: 0,
    inProgressTasks: 1,
    milestones: [
      { id: 'm-4', title: 'Global Multi-Region Edge Mesh', projectId: 'proj-3', dueDate: '2026-10-15', isCompleted: false, progress: 80, taskCount: 2, completedTaskCount: 1 },
    ],
  },
  {
    id: 'proj-4',
    name: 'Design System & Ergonomics',
    code: 'DESIGN-SYS',
    description: 'Unified obsidian tokens, glassmorphic UI components, accessibility compliance, and micro-interactions.',
    status: 'Active',
    health: 'On Track',
    progress: 90,
    departmentId: 'dept-3',
    teamId: 'team-4',
    leadId: 'usr-6',
    leadName: 'Shabnam Nisha',
    startDate: '2026-04-01',
    targetDate: '2026-09-30',
    totalTasks: 2,
    completedTasks: 1,
    blockedTasks: 0,
    inProgressTasks: 1,
    milestones: [
      { id: 'm-5', title: 'Obsidian UI Kit v2.0 Release', projectId: 'proj-4', dueDate: '2026-09-25', isCompleted: true, progress: 100, taskCount: 2, completedTaskCount: 2 },
    ],
  },
  {
    id: 'proj-5',
    name: 'Enterprise Security & QA',
    code: 'SEC-QA',
    description: 'Automated end-to-end regression testing, penetration scanning, and SOC2 compliance monitoring.',
    status: 'Active',
    health: 'At Risk',
    progress: 45,
    departmentId: 'dept-2',
    teamId: 'team-6',
    leadId: 'usr-10',
    leadName: 'Shivani',
    startDate: '2026-07-01',
    targetDate: '2026-12-15',
    totalTasks: 2,
    completedTasks: 0,
    blockedTasks: 1,
    inProgressTasks: 1,
    milestones: [
      { id: 'm-6', title: 'SOC2 Automated Audit Gate', projectId: 'proj-5', dueDate: '2026-10-30', isCompleted: false, progress: 40, taskCount: 2, completedTaskCount: 0 },
    ],
  },
];

// ==========================================
// 4. CLEAN INITIAL TASKS (Clean Template Set)
// ==========================================
export const INITIAL_TASKS: Task[] = [
  {
    id: 'task-1',
    title: 'Finalize Decision Graph Engine core algorithm & memory profiling',
    description: 'Benchmark tree evaluation cycles and optimize AST caching for high-concurrency decision pipelines.',
    projectId: 'proj-1',
    projectName: 'VEIXON Decisions',
    assigneeId: 'usr-1',
    assigneeName: 'V S Sai Siddardh',
    assigneeAvatar: 'https://www.veixon.com/team/siddardha.png',
    creatorId: 'usr-1',
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    progress: 65,
    estimatedHours: 16,
    loggedHours: 10,
    dueDate: '2026-09-18',
    subtasks: [
      { id: 'st-1', title: 'Profile AST node allocation memory heap', isCompleted: true },
      { id: 'st-2', title: 'Implement LRU cache eviction policy', isCompleted: false },
    ],
    blockerIds: [],
    comments: [],
    tags: ['Core Engine', 'Algorithms', 'Profiling'],
    createdAt: '2026-09-01T09:00:00Z',
    updatedAt: '2026-09-10T14:30:00Z',
  },
  {
    id: 'task-2',
    title: 'Configure Stripe Billing webhook handler and AWS KMS signing',
    description: 'Implement secure cryptographic verification for incoming Stripe webhook payloads using AWS KMS key.',
    projectId: 'proj-1',
    projectName: 'VEIXON Decisions',
    assigneeId: 'usr-5',
    assigneeName: 'Arjun J',
    assigneeAvatar: 'https://www.veixon.com/team/ARJUN.png',
    creatorId: 'usr-1',
    status: 'BLOCKED',
    priority: 'CRITICAL',
    progress: 40,
    estimatedHours: 20,
    loggedHours: 8,
    dueDate: '2026-09-20',
    subtasks: [
      { id: 'st-3', title: 'Setup Stripe webhook endpoint scaffolding', isCompleted: true },
      { id: 'st-4', title: 'Configure KMS decryption client', isCompleted: false },
    ],
    blockerIds: ['blk-1'],
    comments: [],
    tags: ['Stripe', 'Billing', 'AWS KMS', 'Security'],
    createdAt: '2026-09-02T10:00:00Z',
    updatedAt: '2026-09-11T16:00:00Z',
  },
  {
    id: 'task-3',
    title: 'Setup DayZero incubation intake pipeline and candidate ranking model',
    description: 'Build automated screening logic and valuation metrics for inbound incubator applications.',
    projectId: 'proj-2',
    projectName: 'DayZero Foundary',
    assigneeId: 'usr-2',
    assigneeName: 'Abhinav Rishi',
    assigneeAvatar: 'https://www.veixon.com/team/Abhinav.png',
    creatorId: 'usr-2',
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    progress: 50,
    estimatedHours: 24,
    loggedHours: 12,
    dueDate: '2026-09-25',
    subtasks: [
      { id: 'st-5', title: 'Define applicant score weighting matrix', isCompleted: true },
    ],
    blockerIds: [],
    comments: [],
    tags: ['Foundary', 'Scoring', 'Pipelines'],
    createdAt: '2026-09-03T11:00:00Z',
    updatedAt: '2026-09-09T17:00:00Z',
  },
  {
    id: 'task-4',
    title: 'Deploy Kubernetes ingress controller with Cloudflare SSL termination',
    description: 'Provision HA ingress controllers across Hyderabad and Mumbai AWS regions with automated SSL failover.',
    projectId: 'proj-3',
    projectName: 'VEIXON Core Infrastructure',
    assigneeId: 'usr-4',
    assigneeName: 'Suhas',
    assigneeAvatar: 'https://www.veixon.com/team/suhas.png',
    creatorId: 'usr-4',
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    progress: 75,
    estimatedHours: 18,
    loggedHours: 14,
    dueDate: '2026-09-22',
    subtasks: [
      { id: 'st-6', title: 'Deploy HA ingress daemonsets', isCompleted: true },
      { id: 'st-7', title: 'Configure Cloudflare origin certificates', isCompleted: true },
    ],
    blockerIds: [],
    comments: [],
    tags: ['Kubernetes', 'Cloudflare', 'Infra', 'SSL'],
    createdAt: '2026-09-04T08:30:00Z',
    updatedAt: '2026-09-11T12:00:00Z',
  },
  {
    id: 'task-5',
    title: 'Publish unified Design Token Library and Framer Motion micro-interactions',
    description: 'Export CSS variables and Tailwind tokens for Obsidian palette and micro-interaction hooks.',
    projectId: 'proj-4',
    projectName: 'Design System & Ergonomics',
    assigneeId: 'usr-6',
    assigneeName: 'Shabnam Nisha',
    assigneeAvatar: 'https://www.veixon.com/team/Shabnam.jpeg',
    creatorId: 'usr-1',
    status: 'COMPLETED',
    priority: 'MEDIUM',
    progress: 100,
    estimatedHours: 12,
    loggedHours: 12,
    dueDate: '2026-09-12',
    subtasks: [
      { id: 'st-8', title: 'Export Figma token JSON', isCompleted: true },
      { id: 'st-9', title: 'Verify contrast ratios in dark mode', isCompleted: true },
    ],
    blockerIds: [],
    comments: [],
    tags: ['Design System', 'Tokens', 'CSS', 'Framer'],
    createdAt: '2026-09-01T10:00:00Z',
    updatedAt: '2026-09-12T09:00:00Z',
  },
  {
    id: 'task-6',
    title: 'Integrate dynamic responsive navigation and active route indicators',
    description: 'Build fluid top navigation tabs with glassmorphism backdrop and zero-lag transition states.',
    projectId: 'proj-4',
    projectName: 'Design System & Ergonomics',
    assigneeId: 'usr-7',
    assigneeName: 'C. Taran Teja',
    assigneeAvatar: 'https://www.veixon.com/team/taran.jpeg',
    creatorId: 'usr-6',
    status: 'IN_PROGRESS',
    priority: 'MEDIUM',
    progress: 55,
    estimatedHours: 14,
    loggedHours: 8,
    dueDate: '2026-09-21',
    subtasks: [
      { id: 'st-10', title: 'Build mobile drawer layout', isCompleted: true },
    ],
    blockerIds: [],
    comments: [],
    tags: ['UI', 'Navigation', 'Frontend', 'Next.js'],
    createdAt: '2026-09-05T13:00:00Z',
    updatedAt: '2026-09-11T18:00:00Z',
  },
  {
    id: 'task-7',
    title: 'Implement automated Playwright regression suite for authentication flow',
    description: 'Create multi-role end-to-end browser tests verifying session persistence and role routing.',
    projectId: 'proj-5',
    projectName: 'Enterprise Security & QA',
    assigneeId: 'usr-10',
    assigneeName: 'Shivani',
    assigneeAvatar: 'https://www.veixon.com/team/shivani.jpeg',
    creatorId: 'usr-1',
    status: 'BLOCKED',
    priority: 'HIGH',
    progress: 25,
    estimatedHours: 16,
    loggedHours: 4,
    dueDate: '2026-09-23',
    subtasks: [
      { id: 'st-11', title: 'Author baseline test scenarios', isCompleted: true },
    ],
    blockerIds: ['blk-2'],
    comments: [],
    tags: ['QA', 'Playwright', 'E2E', 'Automation'],
    createdAt: '2026-09-06T14:00:00Z',
    updatedAt: '2026-09-11T10:00:00Z',
  },
];

// ==========================================
// 5. CLEAN INITIAL BLOCKERS (Clean Template)
// ==========================================
export const INITIAL_BLOCKERS: Blocker[] = [
  {
    id: 'blk-1',
    title: 'AWS KMS Key IAM decryption policy for Stripe webhooks',
    description: 'Arjun J requires IAM permission updates on the KMS encryption key to decode Stripe event payloads in staging.',
    severity: 'CRITICAL',
    status: 'OPEN',
    taskId: 'task-2',
    taskTitle: 'Configure Stripe Billing webhook handler and AWS KMS signing',
    projectId: 'proj-1',
    projectName: 'VEIXON Decisions',
    reporterId: 'usr-5',
    reporterName: 'Arjun J',
    reporterAvatar: 'https://www.veixon.com/team/ARJUN.png',
    dependencyOwnerId: 'usr-4',
    dependencyOwnerName: 'Suhas',
    resolverId: 'usr-4',
    resolverName: 'Suhas',
    reportedAt: '2026-09-11T11:00:00Z',
  },
  {
    id: 'blk-2',
    title: 'Staging Database connection timeout during load testing',
    description: 'PostgreSQL connection pool exhaustion occurs during concurrent Playwright test executions.',
    severity: 'HIGH',
    status: 'OPEN',
    taskId: 'task-7',
    taskTitle: 'Implement automated Playwright regression suite for authentication flow',
    projectId: 'proj-5',
    projectName: 'Enterprise Security & QA',
    reporterId: 'usr-10',
    reporterName: 'Shivani',
    reporterAvatar: 'https://www.veixon.com/team/shivani.jpeg',
    dependencyOwnerId: 'usr-3',
    dependencyOwnerName: 'Shlok Karn',
    resolverId: 'usr-3',
    resolverName: 'Shlok Karn',
    reportedAt: '2026-09-11T09:30:00Z',
  },
];

// ==========================================
// 6. CLEAN INITIAL MEETINGS (Clean Template)
// ==========================================
export const INITIAL_MEETINGS: Meeting[] = [
  {
    id: 'mtg-1',
    title: 'VEIXON Core Engineering Daily Sync',
    description: 'Daily operational alignment across architecture, staging deployments, and critical blockers.',
    agenda: 'Architecture review, staging deployment verification, blocker resolution.',
    meetingUrl: 'https://meet.google.com/vex-core-sync',
    scheduledAt: '2026-09-12T10:00:00Z',
    durationMins: 30,
    organizerId: 'usr-1',
    organizerName: 'V S Sai Siddardh',
    departmentId: 'dept-2',
    teamId: 'team-2',
    status: 'Scheduled',
    attendances: INITIAL_USERS.map((u) => ({
      id: `att-1-${u.id}`,
      meetingId: 'mtg-1',
      userId: u.id,
      userName: u.name,
      userAvatar: u.avatarUrl,
      userRole: u.role,
      status: (u.id === 'usr-10' ? 'ABSENT' : u.id === 'usr-4' ? 'EXCUSED' : 'PRESENT') as MeetingAttendanceStatus,
      missedReason: u.id === 'usr-10' ? ('OTHER' as MissedMeetingReason) : undefined,
      explanationNote: u.id === 'usr-4' ? 'Representing VEIXON on-site AWS cloud architecture audit' : undefined,
      isManagerExcused: u.id === 'usr-4',
      updatedAt: '2026-09-12T09:00:00Z',
    })),
  },
  {
    id: 'mtg-2',
    title: 'Architecture & Tech Review: Decision Graph Engine',
    description: 'In-depth review of memory profiling and AST cache invalidation strategies with CTO.',
    agenda: 'Memory profiling AST cache invalidation.',
    meetingUrl: 'https://meet.google.com/vex-arch-rev',
    scheduledAt: '2026-09-12T14:30:00Z',
    durationMins: 45,
    organizerId: 'usr-3',
    organizerName: 'Shlok Karn',
    departmentId: 'dept-2',
    teamId: 'team-2',
    status: 'Scheduled',
    attendances: [INITIAL_USERS[0], INITIAL_USERS[2], INITIAL_USERS[4]].map((u) => ({
      id: `att-2-${u.id}`,
      meetingId: 'mtg-2',
      userId: u.id,
      userName: u.name,
      userAvatar: u.avatarUrl,
      userRole: u.role,
      status: 'PRESENT' as MeetingAttendanceStatus,
      isManagerExcused: false,
      updatedAt: '2026-09-12T09:00:00Z',
    })),
  },
  {
    id: 'mtg-3',
    title: 'Product & Design Review: Obsidian UI Kit v2.0',
    description: 'Review updated Figma design tokens, glassmorphism specs, and mobile responsiveness.',
    agenda: 'Figma token validation and contrast check.',
    meetingUrl: 'https://meet.google.com/vex-design-rev',
    scheduledAt: '2026-09-13T11:00:00Z',
    durationMins: 40,
    organizerId: 'usr-6',
    organizerName: 'Shabnam Nisha',
    departmentId: 'dept-3',
    teamId: 'team-4',
    status: 'Scheduled',
    attendances: [INITIAL_USERS[0], INITIAL_USERS[5], INITIAL_USERS[6]].map((u) => ({
      id: `att-3-${u.id}`,
      meetingId: 'mtg-3',
      userId: u.id,
      userName: u.name,
      userAvatar: u.avatarUrl,
      userRole: u.role,
      status: 'PRESENT' as MeetingAttendanceStatus,
      isManagerExcused: false,
      updatedAt: '2026-09-12T09:00:00Z',
    })),
  },
];

// ==========================================
// 7. CLEAN INITIAL LEAVE REQUESTS
// ==========================================
export const INITIAL_LEAVES: LeaveRequest[] = [
  {
    id: 'lev-1',
    userId: 'usr-4',
    userName: 'Suhas',
    userAvatar: 'https://www.veixon.com/team/suhas.png',
    userJobTitle: 'Cloud & Infrastructure Lead',
    departmentName: 'Cloud & Infrastructure',
    leaveType: 'ANNUAL',
    startDate: '2026-09-12',
    endDate: '2026-09-12',
    isHalfDay: false,
    totalDays: 1,
    reason: 'On-site technical evaluation and AWS data center interconnect audit.',
    handoverCompleted: true,
    status: 'APPROVED',
    approverId: 'usr-1',
    approverName: 'V S Sai Siddardh',
    decisionAt: '2026-09-10T14:00:00Z',
    createdAt: '2026-09-10T11:00:00Z',
  },
  {
    id: 'lev-2',
    userId: 'usr-9',
    userName: 'Sreeshith',
    userAvatar: 'https://www.veixon.com/team/sreeshith.png',
    userJobTitle: 'Lead DevOps / SRE',
    departmentName: 'Cloud & Infrastructure',
    leaveType: 'ANNUAL',
    startDate: '2026-09-15',
    endDate: '2026-09-16',
    isHalfDay: false,
    totalDays: 2,
    reason: 'Attending Kubernetes & Cloud Native Architecture Summit 2026.',
    handoverCompleted: true,
    status: 'PENDING_APPROVAL',
    createdAt: '2026-09-11T16:00:00Z',
  },
];

// ==========================================
// 8. OFFICIAL GOALS & OKRS (Clean Template)
// ==========================================
export const INITIAL_GOALS: Goal[] = [
  {
    id: 'goal-1',
    title: 'Deploy VEIXON Decisions v1.0 Production Platform',
    description: 'Enterprise decision intelligence platform deployment.',
    departmentId: 'dept-2',
    departmentName: 'Engineering & Technology',
    ownerId: 'usr-1',
    ownerName: 'V S Sai Siddardh',
    targetDate: '2026-10-31',
    progress: 74,
    status: 'ON_TRACK',
    tier: 'COMPANY',
    keyResults: [
      { id: 'kr-1', title: 'Achieve sub-50ms decision execution SLA', targetValue: 50, currentValue: 42, metricUnit: 'ms', progress: 84 },
      { id: 'kr-2', title: 'Complete Stripe & KMS enterprise security audit', targetValue: 100, currentValue: 65, metricUnit: '%', progress: 65 },
    ],
  },
  {
    id: 'goal-2',
    title: 'Achieve 99.99% Infrastructure Uptime & Zero-Trust Mesh',
    description: 'Multi-region failover and edge acceleration mesh.',
    departmentId: 'dept-4',
    departmentName: 'Cloud & Infrastructure',
    ownerId: 'usr-4',
    ownerName: 'Suhas',
    targetDate: '2026-12-31',
    progress: 88,
    status: 'ON_TRACK',
    tier: 'DEPARTMENT',
    keyResults: [
      { id: 'kr-3', title: 'Multi-region failover latency under 2 seconds', targetValue: 2, currentValue: 1.4, metricUnit: 's', progress: 92 },
    ],
  },
  {
    id: 'goal-3',
    title: 'Ship Obsidian UI Kit v2.0 with Full Accessibility Compliance',
    description: 'Accessible tokens, micro-interactions, and glassmorphic aesthetics.',
    departmentId: 'dept-3',
    departmentName: 'Product & Design Systems',
    ownerId: 'usr-6',
    ownerName: 'Shabnam Nisha',
    targetDate: '2026-09-30',
    progress: 92,
    status: 'ON_TRACK',
    tier: 'DEPARTMENT',
    keyResults: [
      { id: 'kr-4', title: 'WCAG 2.1 AA Contrast and Navigation verification', targetValue: 100, currentValue: 95, metricUnit: '%', progress: 95 },
    ],
  },
];

// ==========================================
// 9. CLEAN INITIAL AUDIT LOGS
// ==========================================
export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'audit-1',
    actorId: 'usr-1',
    actorName: 'V S Sai Siddardh',
    actorAvatar: 'https://www.veixon.com/team/siddardha.png',
    actorRole: 'DIRECTOR',
    action: 'SYSTEM_INITIALIZED',
    entityType: 'System',
    entityId: 'SYS-VEIXON-CORE',
    entityTitle: 'VEIXON Command Center v2.4 Release',
    details: 'VEIXON Command Center initialized with clean enterprise template and telemetry logging.',
    timestamp: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
  },
  {
    id: 'audit-2',
    actorId: 'usr-4',
    actorName: 'Suhas',
    actorAvatar: 'https://www.veixon.com/team/suhas.png',
    actorRole: 'MANAGER',
    action: 'LEAVE_REQUEST_APPROVED',
    entityType: 'LeaveRequest',
    entityId: 'lev-1',
    entityTitle: 'Duty Leave: AWS Interconnect Audit',
    details: 'Duty leave approved by Director V S Sai Siddardh for technical audit.',
    timestamp: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
  },
  {
    id: 'audit-3',
    actorId: 'usr-5',
    actorName: 'Arjun J',
    actorAvatar: 'https://www.veixon.com/team/ARJUN.png',
    actorRole: 'EMPLOYEE',
    action: 'BLOCKER_REPORTED',
    entityType: 'Blocker',
    entityId: 'blk-1',
    entityTitle: 'AWS KMS Key IAM decryption policy',
    details: 'Blocker flagged on VEIXON Decisions and assigned to Cloud & Infrastructure Lead.',
    timestamp: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
  },
  {
    id: 'audit-4',
    actorId: 'usr-6',
    actorName: 'Shabnam Nisha',
    actorAvatar: 'https://www.veixon.com/team/Shabnam.jpeg',
    actorRole: 'EMPLOYEE',
    action: 'TASK_COMPLETED',
    entityType: 'Task',
    entityId: 'task-5',
    entityTitle: 'Publish unified Design Token Library',
    details: 'Task completed and merged into main design branch with Obsidian token verification.',
    timestamp: new Date(Date.now() - 150 * 60 * 1000).toISOString(),
  },
];

// ==========================================
// 10. CLEAN INITIAL NOTIFICATIONS
// ==========================================
export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    userId: 'usr-1',
    title: 'Critical Blocker Flagged',
    message: 'Arjun J reported an AWS KMS IAM policy blocker on VEIXON Decisions.',
    type: 'BLOCKER',
    severity: 'danger',
    isRead: false,
    createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
  {
    id: 'notif-2',
    userId: 'usr-1',
    title: 'Duty Leave Awaiting Review',
    message: 'Sreeshith submitted a duty leave request for Kubernetes Summit 2026.',
    type: 'LEAVE_REQUEST',
    severity: 'info',
    isRead: false,
    createdAt: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'notif-3',
    userId: 'usr-1',
    title: 'Standup Scheduled at 10:00 AM',
    message: 'VEIXON Core Engineering Daily Sync starts in 20 minutes.',
    type: 'CHECKIN',
    severity: 'info',
    isRead: true,
    createdAt: new Date(Date.now() - 120 * 60 * 1000).toISOString(),
  },
];

// ==========================================
// 11. WEEKLY CHECKINS
// ==========================================
export const INITIAL_CHECKINS: WeeklyCheckin[] = INITIAL_USERS.map((u, i) => ({
  id: `chk-${i + 1}`,
  userId: u.id,
  userName: u.name,
  userAvatar: u.avatarUrl,
  userJobTitle: u.jobTitle,
  departmentName: u.departmentName,
  weekNumber: 37,
  year: 2026,
  completedHighlights: 'Completed core refactoring, merged staging branches, and resolved API performance bottlenecks.',
  upcomingPriorities: 'Sprint delivery, automated regression suites, and cross-browser accessibility audit.',
  activeBlockers: i === 4 ? 'Waiting on AWS KMS IAM decryption policy.' : 'None',
  supportNeeded: 'None, fully aligned.',
  confidence: (i === 4 ? 'MEDIUM' : 'HIGH') as any,
  isReviewed: i !== 4,
  submittedAt: new Date(Date.now() - (i + 1) * 7200000).toISOString(),
}));

// ==========================================
// 12. PROACTIVE AI INSIGHTS
// ==========================================
export const PROACTIVE_INSIGHTS: InsightCard[] = [
  {
    id: 'ins-1',
    title: 'Stripe KMS Blocker Impacting Staging Release',
    description: 'Arjun J reported an AWS KMS IAM policy blocker on VEIXON Decisions. Resolving this unblocks 2 related milestones.',
    category: 'blockers',
    severity: 'critical',
    evidenceCitations: [
      { label: 'Blocker #1', entityType: 'Blocker', entityId: 'blk-1' },
      { label: 'Task #2', entityType: 'Task', entityId: 'task-2' },
    ],
    suggestedAction: 'Assign IAM policy update to Suhas (DevOps Lead)',
    actionLabel: 'Assign & Unblock',
  },
  {
    id: 'ins-2',
    title: 'Engineering Velocity Nominal',
    description: 'Core projects running on schedule with 10 active engineering team members deployed.',
    category: 'velocity',
    severity: 'positive',
    evidenceCitations: [{ label: '1 Completed Task', entityType: 'Task', entityId: 'task-5' }],
    suggestedAction: 'View Work Board',
    actionLabel: 'Open Kanban',
  },
];
