const { PrismaClient } = require('@prisma/client');

const prisma = new PrismaClient();

const VEIXON_USERS = [
  {
    id: 'usr-1',
    name: 'V S Sai Siddardh',
    email: 'siddhardh@veixon.tech',
    password: 'password123',
    role: 'DIRECTOR',
    jobTitle: 'Co-founder & Director',
    departmentName: 'Executive Engineering',
    avatarUrl: 'https://www.veixon.com/team/siddardha.png',
    phone: '+91 96185 87055',
    bio: 'Strategic Architecture, Operations, and AI Systems across VEIXON.Tech.',
    skills: JSON.stringify(['Strategic Architecture', 'Operations', 'Leadership', 'AI Systems']),
    emergencyContact: 'Executive Office - +91 96185 87055',
    joinedDate: 'January 15, 2023',
    workPreference: 'On-site',
    status: 'WORKING',
  },
  {
    id: 'usr-2',
    name: 'Abhinav Rishi',
    email: 'abhinav@veixon.tech',
    password: 'password123',
    role: 'ADMIN',
    jobTitle: 'Founder & CEO',
    departmentName: 'Executive Leadership',
    avatarUrl: 'https://www.veixon.com/team/Abhinav.png',
    phone: '+91 98000 00001',
    bio: 'Company vision, enterprise partnerships, and operational scaling.',
    skills: JSON.stringify(['Executive Leadership', 'Product Vision', 'Business Scaling']),
    emergencyContact: 'HQ Operations - (555) 019-2834',
    joinedDate: 'January 1, 2023',
    workPreference: 'On-site',
    status: 'WORKING',
  },
  {
    id: 'usr-3',
    name: 'Shlok Karn',
    email: 'shlok@veixon.tech',
    password: 'password123',
    role: 'ADMIN',
    jobTitle: 'Co-founder & CTO',
    departmentName: 'Technology & Architecture',
    avatarUrl: 'https://www.veixon.com/team/shlok.jpeg',
    phone: '+91 98000 00002',
    bio: 'Technology roadmaps, deep engineering standards, and infrastructure.',
    skills: JSON.stringify(['Distributed Systems', 'Cloud Infra', 'System Architecture']),
    emergencyContact: 'HQ Operations - (555) 018-9921',
    joinedDate: 'January 1, 2023',
    workPreference: 'On-site',
    status: 'WORKING',
  },
  {
    id: 'usr-4',
    name: 'Suhas',
    email: 'suhas@veixon.tech',
    password: 'password123',
    role: 'MANAGER',
    jobTitle: 'Cloud & Infrastructure Lead',
    departmentName: 'Cloud & DevOps',
    avatarUrl: 'https://www.veixon.com/team/suhas.png',
    phone: '+91 98000 00003',
    bio: 'Kubernetes orchestration, multi-region failover, and CI/CD pipelines.',
    skills: JSON.stringify(['AWS', 'Kubernetes', 'Terraform', 'CI/CD', 'Security']),
    emergencyContact: 'Ops Emergency - (555) 012-7766',
    joinedDate: 'March 15, 2023',
    workPreference: 'On-site',
    status: 'WORKING',
  },
  {
    id: 'usr-5',
    name: 'Arjun J',
    email: 'arjun@veixon.tech',
    password: 'password123',
    role: 'EMPLOYEE',
    jobTitle: 'Software Engineer',
    departmentName: 'Backend Engineering',
    avatarUrl: 'https://www.veixon.com/team/ARJUN.png',
    phone: '+91 98000 00004',
    bio: 'Building resilient microservices, high-throughput queues, and cache layers.',
    skills: JSON.stringify(['Node.js', 'Go', 'Redis', 'PostgreSQL', 'Microservices']),
    emergencyContact: 'Family Contact - (555) 014-8833',
    joinedDate: 'June 1, 2023',
    workPreference: 'On-site',
    status: 'WORKING',
  },
  {
    id: 'usr-6',
    name: 'Shabnam Nisha',
    email: 'shabnam@veixon.tech',
    password: 'password123',
    role: 'EMPLOYEE',
    jobTitle: 'Lead Product Designer',
    departmentName: 'Design Systems',
    avatarUrl: 'https://www.veixon.com/team/Shabnam.jpeg',
    phone: '+91 98000 00005',
    bio: 'Crafting VEIXON Command Center ergonomics, design tokens, and user experience.',
    skills: JSON.stringify(['Figma', 'Design Systems', 'UI/UX', 'Design Tokens']),
    emergencyContact: 'Family Contact - (555) 016-5544',
    joinedDate: 'May 1, 2023',
    workPreference: 'On-site',
    status: 'WORKING',
  },
  {
    id: 'usr-7',
    name: 'C. Taran Teja',
    email: 'taran@veixon.tech',
    password: 'password123',
    role: 'EMPLOYEE',
    jobTitle: 'Frontend Engineer',
    departmentName: 'Web & Applications',
    avatarUrl: 'https://www.veixon.com/team/taran.jpeg',
    phone: '+91 98000 00006',
    bio: 'Delivering responsive, high-performance web applications and fluid UI animations.',
    skills: JSON.stringify(['React', 'Next.js', 'TypeScript', 'Tailwind CSS']),
    emergencyContact: 'Family Contact - (555) 017-3322',
    joinedDate: 'July 1, 2023',
    workPreference: 'On-site',
    status: 'WORKING',
  },
  {
    id: 'usr-8',
    name: 'Navya',
    email: 'navya@veixon.tech',
    password: 'password123',
    role: 'HR',
    jobTitle: 'Head of People & Operations',
    departmentName: 'People & Culture',
    avatarUrl: 'https://www.veixon.com/team/NAVYA.jpeg',
    phone: '+91 98000 00007',
    bio: 'Fostering company culture, managing leaves, on-duty approvals, and team wellness.',
    skills: JSON.stringify(['People Operations', 'HR', 'Talent Management', 'Culture']),
    emergencyContact: 'Operations - (555) 018-4455',
    joinedDate: 'April 1, 2023',
    workPreference: 'On-site',
    status: 'WORKING',
  },
  {
    id: 'usr-9',
    name: 'Sreeshith',
    email: 'sreeshith@veixon.tech',
    password: 'password123',
    role: 'EMPLOYEE',
    jobTitle: 'Lead DevOps / SRE',
    departmentName: 'Infrastructure & SRE',
    avatarUrl: 'https://www.veixon.com/team/sreeshith.png',
    phone: '+91 98000 00008',
    bio: 'Uptime monitoring, deployment automation, and zero-downtime release pipelines.',
    skills: JSON.stringify(['DevOps', 'Kubernetes', 'Prometheus', 'Grafana']),
    emergencyContact: 'Emergency - (555) 019-5566',
    joinedDate: 'August 1, 2023',
    workPreference: 'On-site',
    status: 'WORKING',
  },
  {
    id: 'usr-10',
    name: 'Shivani',
    email: 'shivani@veixon.tech',
    password: 'password123',
    role: 'EMPLOYEE',
    jobTitle: 'QA & Security Engineer',
    departmentName: 'Quality Assurance',
    avatarUrl: 'https://www.veixon.com/team/shivani.jpeg',
    phone: '+91 98000 00009',
    bio: 'End-to-end test automation, penetration testing, and software quality.',
    skills: JSON.stringify(['QA Automation', 'Playwright', 'Security Testing', 'Jest']),
    emergencyContact: 'Emergency - (555) 020-6677',
    joinedDate: 'September 1, 2023',
    workPreference: 'On-site',
    status: 'WORKING',
  },
];

async function seed() {
  console.log('Seeding VEIXON official team members into SQLite database...');
  for (const u of VEIXON_USERS) {
    await prisma.user.upsert({
      where: { email: u.email },
      update: u,
      create: u,
    });
  }
  console.log('Seeding complete! Total users:', VEIXON_USERS.length);
}

seed()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
